# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Enums
          # Container for enum describing possible types of a conversion action.
          class ConversionActionTypeEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Possible types of a conversion action.
            module ConversionActionType
              # Not specified.
              UNSPECIFIED = 0

              # Used for return value only. Represents value unknown in this version.
              UNKNOWN = 1

              # Conversions that occur when a user clicks on an ad's call extension.
              AD_CALL = 2

              # Conversions that occur when a user on a mobile device clicks a phone
              # number.
              CLICK_TO_CALL = 3

              # Conversions that occur when a user downloads a mobile app from the Google
              # Play Store.
              GOOGLE_PLAY_DOWNLOAD = 4

              # Conversions that occur when a user makes a purchase in an app through
              # Android billing.
              GOOGLE_PLAY_IN_APP_PURCHASE = 5

              # Call conversions that are tracked by the advertiser and uploaded.
              UPLOAD_CALLS = 6

              # Conversions that are tracked by the advertiser and uploaded with
              # attributed clicks.
              UPLOAD_CLICKS = 7

              # Conversions that occur on a webpage.
              WEBPAGE = 8

              # Conversions that occur when a user calls a dynamically-generated phone
              # number from an advertiser's website.
              WEBSITE_CALL = 9
            end
          end
        end
      end
    end
  end
end
