# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Enums
          # Container for distance buckets of a user’s distance from an advertiser’s
          # location extension.
          class DistanceBucketEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # The distance bucket for a user’s distance from an advertiser’s location
            # extension.
            module DistanceBucket
              # Not specified.
              UNSPECIFIED = 0

              # Used for return value only. Represents value unknown in this version.
              UNKNOWN = 1

              # User was within 700m of the location.
              WITHIN_700M = 2

              # User was within 1KM of the location.
              WITHIN_1KM = 3

              # User was within 5KM of the location.
              WITHIN_5KM = 4

              # User was within 10KM of the location.
              WITHIN_10KM = 5

              # User was within 15KM of the location.
              WITHIN_15KM = 6

              # User was within 20KM of the location.
              WITHIN_20KM = 7

              # User was within 25KM of the location.
              WITHIN_25KM = 8

              # User was within 30KM of the location.
              WITHIN_30KM = 9

              # User was within 35KM of the location.
              WITHIN_35KM = 10

              # User was within 40KM of the location.
              WITHIN_40KM = 11

              # User was within 45KM of the location.
              WITHIN_45KM = 12

              # User was within 50KM of the location.
              WITHIN_50KM = 13

              # User was within 55KM of the location.
              WITHIN_55KM = 14

              # User was within 60KM of the location.
              WITHIN_60KM = 15

              # User was within 65KM of the location.
              WITHIN_65KM = 16

              # User was beyond 65KM of the location.
              BEYOND_65KM = 17

              # User was within 0.7 miles of the location.
              WITHIN_0_7MILES = 18

              # User was within 1 mile of the location.
              WITHIN_1MILE = 19

              # User was within 5 miles of the location.
              WITHIN_5MILES = 20

              # User was within 10 miles of the location.
              WITHIN_10MILES = 21

              # User was within 15 miles of the location.
              WITHIN_15MILES = 22

              # User was within 20 miles of the location.
              WITHIN_20MILES = 23

              # User was within 25 miles of the location.
              WITHIN_25MILES = 24

              # User was within 30 miles of the location.
              WITHIN_30MILES = 25

              # User was within 35 miles of the location.
              WITHIN_35MILES = 26

              # User was within 40 miles of the location.
              WITHIN_40MILES = 27

              # User was beyond 40 miles of the location.
              BEYOND_40MILES = 28
            end
          end
        end
      end
    end
  end
end
