# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Enums
          # Container for enum that determines if the described artifact is a resource
          # or a field, and if it is a field, when it segments search queries.
          class GoogleAdsFieldCategoryEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # The category of the artifact.
            module GoogleAdsFieldCategory
              # Unspecified
              UNSPECIFIED = 0

              # Unknown
              UNKNOWN = 1

              # The described artifact is a resource.
              RESOURCE = 2

              # The described artifact is a field and is an attribute of a resource.
              # Including a resource attribute field in a query may segment the query if
              # the resource to which it is attributed segments the resource found in
              # the FROM clause.
              ATTRIBUTE = 3

              # The described artifact is a field and always segments search queries.
              SEGMENT = 5

              # The described artifact is a field and is a metric. It never segments
              # search queries.
              METRIC = 6
            end
          end
        end
      end
    end
  end
end
