# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Enums
          # Container for enum describing possible payment modes.
          class PaymentModeEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Enum describing possible payment modes.
            module PaymentMode
              # Not specified.
              UNSPECIFIED = 0

              # Used for return value only. Represents value unknown in this version.
              UNKNOWN = 1

              # Pay per click.
              CLICKS = 4

              # Pay per conversion value. This mode is only supported by campaigns with
              # AdvertisingChannelType.HOTEL, BiddingStrategyType.COMMISSION, and
              # BudgetType.HOTEL_ADS_COMMISSION.
              CONVERSION_VALUE = 5

              # Pay per conversion. This mode is only supported by campaigns with
              # AdvertisingChannelType.DISPLAY (excluding
              # AdvertisingChannelSubType.DISPLAY_GMAIL), BiddingStrategyType.TARGET_CPA,
              # and BudgetType.FIXED_CPA. The customer must also be eligible for this
              # mode. See Customer.eligibility_failure_reasons for details.
              CONVERSIONS = 6

              # Pay per guest stay value. This mode is only supported by campaigns with
              # AdvertisingChannelType.HOTEL, BiddingStrategyType.COMMISSION, and
              # BudgetType.HOTEL_ADS_COMMISSION.
              GUEST_STAY = 7
            end
          end
        end
      end
    end
  end
end
