# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Enums
          # Values for Promotion placeholder fields.
          class PromotionPlaceholderFieldEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Possible values for Promotion placeholder fields.
            module PromotionPlaceholderField
              # Not specified.
              UNSPECIFIED = 0

              # Used for return value only. Represents value unknown in this version.
              UNKNOWN = 1

              # Data Type: STRING. The text that appears on the ad when the extension is
              # shown.
              PROMOTION_TARGET = 2

              # Data Type: STRING. Allows you to add "up to" phrase to the promotion,
              # in case you have variable promotion rates.
              DISCOUNT_MODIFIER = 3

              # Data Type: INT64. Takes a value in micros, where 1 million micros
              # represents 1%, and is shown as a percentage when rendered.
              PERCENT_OFF = 4

              # Data Type: MONEY. Requires a currency and an amount of money.
              MONEY_AMOUNT_OFF = 5

              # Data Type: STRING. A string that the user enters to get the discount.
              PROMOTION_CODE = 6

              # Data Type: MONEY. A minimum spend before the user qualifies for the
              # promotion.
              ORDERS_OVER_AMOUNT = 7

              # Data Type: DATE. The start date of the promotion.
              PROMOTION_START = 8

              # Data Type: DATE. The end date of the promotion.
              PROMOTION_END = 9

              # Data Type: STRING. Describes the associated event for the promotion using
              # one of the PromotionExtensionOccasion enum values, for example NEW_YEARS.
              OCCASION = 10

              # Data Type: URL_LIST. Final URLs to be used in the ad when using Upgraded
              # URLs.
              FINAL_URLS = 11

              # Data Type: URL_LIST. Final mobile URLs for the ad when using Upgraded
              # URLs.
              FINAL_MOBILE_URLS = 12

              # Data Type: URL. Tracking template for the ad when using Upgraded URLs.
              TRACKING_URL = 13

              # Data Type: STRING. A string represented by a language code for the
              # promotion.
              LANGUAGE = 14

              # Data Type: STRING. Final URL suffix for the ad when using parallel
              # tracking.
              FINAL_URL_SUFFIX = 15
            end
          end
        end
      end
    end
  end
end
