# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Common
          # Collection of urls that is tagged with a unique identifier.
          # @!attribute [rw] url_collection_id
          #   @return [Google::Protobuf::StringValue]
          #     Unique identifier for this UrlCollection instance.
          # @!attribute [rw] final_urls
          #   @return [Array<Google::Protobuf::StringValue>]
          #     A list of possible final URLs.
          # @!attribute [rw] final_mobile_urls
          #   @return [Array<Google::Protobuf::StringValue>]
          #     A list of possible final mobile URLs.
          # @!attribute [rw] tracking_url_template
          #   @return [Google::Protobuf::StringValue]
          #     URL template for constructing a tracking URL.
          class UrlCollection
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
