# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Services
          # Request message for {Google::Ads::GoogleAds::V3::Services::AdGroupAdService::Client#get_ad_group_ad AdGroupAdService.GetAdGroupAd}.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Required. The resource name of the ad to fetch.
          class GetAdGroupAdRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Request message for {Google::Ads::GoogleAds::V3::Services::AdGroupAdService::Client#mutate_ad_group_ads AdGroupAdService.MutateAdGroupAds}.
          # @!attribute [rw] customer_id
          #   @return [String]
          #     Required. The ID of the customer whose ads are being modified.
          # @!attribute [rw] operations
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::AdGroupAdOperation>]
          #     Required. The list of operations to perform on individual ads.
          # @!attribute [rw] partial_failure
          #   @return [Boolean]
          #     If true, successful operations will be carried out and invalid
          #     operations will return errors. If false, all operations will be carried
          #     out in one transaction if and only if they are all valid.
          #     Default is false.
          # @!attribute [rw] validate_only
          #   @return [Boolean]
          #     If true, the request is validated but not executed. Only errors are
          #     returned, not results.
          class MutateAdGroupAdsRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A single operation (create, update, remove) on an ad group ad.
          # @!attribute [rw] update_mask
          #   @return [Google::Protobuf::FieldMask]
          #     FieldMask that determines which resource fields are modified in an update.
          # @!attribute [rw] policy_validation_parameter
          #   @return [Google::Ads::GoogleAds::V3::Common::PolicyValidationParameter]
          #     Configuration for how policies are validated.
          # @!attribute [rw] create
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroupAd]
          #     Create operation: No resource name is expected for the new ad.
          # @!attribute [rw] update
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroupAd]
          #     Update operation: The ad is expected to have a valid resource name.
          # @!attribute [rw] remove
          #   @return [String]
          #     Remove operation: A resource name for the removed ad is expected,
          #     in this format:
          #
          #     `customers/{customer_id}/adGroupAds/{ad_group_id}~{ad_id}`
          class AdGroupAdOperation
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Response message for an ad group ad mutate.
          # @!attribute [rw] partial_failure_error
          #   @return [Google::Rpc::Status]
          #     Errors that pertain to operation failures in the partial failure mode.
          #     Returned only when partial_failure = true and all errors occur inside the
          #     operations. If any errors occur outside the operations (e.g. auth errors),
          #     we return an RPC level error.
          # @!attribute [rw] results
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::MutateAdGroupAdResult>]
          #     All results for the mutate.
          class MutateAdGroupAdsResponse
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # The result for the ad mutate.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     The resource name returned for successful operations.
          class MutateAdGroupAdResult
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
