# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Services
          # Request message for {Google::Ads::GoogleAds::V3::Services::CustomerManagerLinkService::Client#get_customer_manager_link CustomerManagerLinkService.GetCustomerManagerLink}.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Required. The resource name of the CustomerManagerLink to fetch.
          class GetCustomerManagerLinkRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Request message for {Google::Ads::GoogleAds::V3::Services::CustomerManagerLinkService::Client#mutate_customer_manager_link CustomerManagerLinkService.MutateCustomerManagerLink}.
          # @!attribute [rw] customer_id
          #   @return [String]
          #     Required. The ID of the customer whose customer manager links are being modified.
          # @!attribute [rw] operations
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::CustomerManagerLinkOperation>]
          #     Required. The list of operations to perform on individual customer manager links.
          class MutateCustomerManagerLinkRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Request message for {Google::Ads::GoogleAds::V3::Services::CustomerManagerLinkService::Client#move_manager_link CustomerManagerLinkService.MoveManagerLink}.
          # @!attribute [rw] customer_id
          #   @return [String]
          #     Required. The ID of the client customer that is being moved.
          # @!attribute [rw] previous_customer_manager_link
          #   @return [String]
          #     Required. The resource name of the previous CustomerManagerLink.
          #     The resource name has the form:
          #     `customers/{customer_id}/customerManagerLinks/{manager_customer_id}~{manager_link_id}`
          # @!attribute [rw] new_manager
          #   @return [String]
          #     Required. The resource name of the new manager customer that the client wants to move
          #     to. Customer resource names have the format: "customers/\\{customer_id}"
          class MoveManagerLinkRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Updates the status of a CustomerManagerLink.
          # The following actions are possible:
          # 1. Update operation with status ACTIVE accepts a pending invitation.
          # 2. Update operation with status REFUSED declines a pending invitation.
          # 3. Update operation with status INACTIVE terminates link to manager.
          # @!attribute [rw] update_mask
          #   @return [Google::Protobuf::FieldMask]
          #     FieldMask that determines which resource fields are modified in an update.
          # @!attribute [rw] update
          #   @return [Google::Ads::GoogleAds::V3::Resources::CustomerManagerLink]
          #     Update operation: The link is expected to have a valid resource name.
          class CustomerManagerLinkOperation
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Response message for a CustomerManagerLink mutate.
          # @!attribute [rw] results
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::MutateCustomerManagerLinkResult>]
          #     A result that identifies the resource affected by the mutate request.
          class MutateCustomerManagerLinkResponse
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Response message for a CustomerManagerLink moveManagerLink.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Returned for successful operations. Represents a CustomerManagerLink
          #     resource of the newly created link between client customer and new manager
          #     customer.
          class MoveManagerLinkResponse
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # The result for the customer manager link mutate.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Returned for successful operations.
          class MutateCustomerManagerLinkResult
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
