# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Services
          # Request message for {Google::Ads::GoogleAds::V3::Services::FeedItemTargetService::Client#get_feed_item_target FeedItemTargetService.GetFeedItemTarget}.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Required. The resource name of the feed item targets to fetch.
          class GetFeedItemTargetRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Request message for {Google::Ads::GoogleAds::V3::Services::FeedItemTargetService::Client#mutate_feed_item_targets FeedItemTargetService.MutateFeedItemTargets}.
          # @!attribute [rw] customer_id
          #   @return [String]
          #     Required. The ID of the customer whose feed item targets are being modified.
          # @!attribute [rw] operations
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::FeedItemTargetOperation>]
          #     Required. The list of operations to perform on individual feed item targets.
          class MutateFeedItemTargetsRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A single operation (create, remove) on an feed item target.
          # @!attribute [rw] create
          #   @return [Google::Ads::GoogleAds::V3::Resources::FeedItemTarget]
          #     Create operation: No resource name is expected for the new feed item
          #     target.
          # @!attribute [rw] remove
          #   @return [String]
          #     Remove operation: A resource name for the removed feed item target is
          #     expected, in this format:
          #
          #     `customers/{customer_id}/feedItemTargets/{feed_id}~{feed_item_id}~{feed_item_target_type}~{feed_item_target_id}`
          class FeedItemTargetOperation
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Response message for an feed item target mutate.
          # @!attribute [rw] results
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::MutateFeedItemTargetResult>]
          #     All results for the mutate.
          class MutateFeedItemTargetsResponse
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # The result for the feed item target mutate.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Returned for successful operations.
          class MutateFeedItemTargetResult
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
