# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Services
          # Request message for fetching all accessible payments accounts.
          # @!attribute [rw] customer_id
          #   @return [String]
          #     Required. The ID of the customer to apply the PaymentsAccount list operation to.
          class ListPaymentsAccountsRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Response message for {Google::Ads::GoogleAds::V3::Services::PaymentsAccountService::Client#list_payments_accounts PaymentsAccountService.ListPaymentsAccounts}.
          # @!attribute [rw] payments_accounts
          #   @return [Array<Google::Ads::GoogleAds::V3::Resources::PaymentsAccount>]
          #     The list of accessible payments accounts.
          class ListPaymentsAccountsResponse
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
