# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Errors
          # Container for enum describing possible customer errors.
          class CustomerErrorEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Set of errors that are related to requests dealing with Customer.
            # Next id: 26
            module CustomerError
              # Enum unspecified.
              UNSPECIFIED = 0

              # The received error code is not known in this version.
              UNKNOWN = 1

              # Customer status is not allowed to be changed from DRAFT and CLOSED.
              # Currency code and at least one of country code and time zone needs to be
              # set when status is changed to ENABLED.
              STATUS_CHANGE_DISALLOWED = 2

              # CustomerService cannot get a customer that has not been fully set up.
              ACCOUNT_NOT_SET_UP = 3
            end
          end
        end
      end
    end
  end
end
