# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Errors
          # Container for enum describing possible shared set errors.
          class SharedSetErrorEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Enum describing possible shared set errors.
            module SharedSetError
              # Enum unspecified.
              UNSPECIFIED = 0

              # The received error code is not known in this version.
              UNKNOWN = 1

              # The customer cannot create this type of shared set.
              CUSTOMER_CANNOT_CREATE_SHARED_SET_OF_THIS_TYPE = 2

              # A shared set with this name already exists.
              DUPLICATE_NAME = 3

              # Removed shared sets cannot be mutated.
              SHARED_SET_REMOVED = 4

              # The shared set cannot be removed because it is in use.
              SHARED_SET_IN_USE = 5
            end
          end
        end
      end
    end
  end
end
