# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Resources
          # An ad group criterion simulation. Supported combinations of advertising
          # channel type, criterion type, simulation type, and simulation modification
          # method are detailed below respectively.
          #
          # 1. DISPLAY - KEYWORD - CPC_BID - UNIFORM
          # 2. SEARCH - KEYWORD - CPC_BID - UNIFORM
          # 3. SHOPPING - LISTING_GROUP - CPC_BID - UNIFORM
          # @!attribute [r] resource_name
          #   @return [String]
          #     Output only. The resource name of the ad group criterion simulation.
          #     Ad group criterion simulation resource names have the form:
          #
          #     `customers/{customer_id}/adGroupCriterionSimulations/{ad_group_id}~{criterion_id}~{type}~{modification_method}~{start_date}~{end_date}`
          # @!attribute [r] ad_group_id
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. AdGroup ID of the simulation.
          # @!attribute [r] criterion_id
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. Criterion ID of the simulation.
          # @!attribute [r] type
          #   @return [Google::Ads::GoogleAds::V3::Enums::SimulationTypeEnum::SimulationType]
          #     Output only. The field that the simulation modifies.
          # @!attribute [r] modification_method
          #   @return [Google::Ads::GoogleAds::V3::Enums::SimulationModificationMethodEnum::SimulationModificationMethod]
          #     Output only. How the simulation modifies the field.
          # @!attribute [r] start_date
          #   @return [Google::Protobuf::StringValue]
          #     Output only. First day on which the simulation is based, in YYYY-MM-DD format.
          # @!attribute [r] end_date
          #   @return [Google::Protobuf::StringValue]
          #     Output only. Last day on which the simulation is based, in YYYY-MM-DD format.
          # @!attribute [r] cpc_bid_point_list
          #   @return [Google::Ads::GoogleAds::V3::Common::CpcBidSimulationPointList]
          #     Output only. Simulation points if the simulation type is CPC_BID.
          class AdGroupCriterionSimulation
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
