# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Resources
          # A campaign criterion.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Immutable. The resource name of the campaign criterion.
          #     Campaign criterion resource names have the form:
          #
          #     `customers/{customer_id}/campaignCriteria/{campaign_id}~{criterion_id}`
          # @!attribute [rw] campaign
          #   @return [Google::Protobuf::StringValue]
          #     Immutable. The campaign to which the criterion belongs.
          # @!attribute [r] criterion_id
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. The ID of the criterion.
          #
          #     This field is ignored during mutate.
          # @!attribute [rw] bid_modifier
          #   @return [Google::Protobuf::FloatValue]
          #     The modifier for the bids when the criterion matches. The modifier must be
          #     in the range: 0.1 - 10.0. Most targetable criteria types support modifiers.
          #     Use 0 to opt out of a Device type.
          # @!attribute [rw] negative
          #   @return [Google::Protobuf::BoolValue]
          #     Immutable. Whether to target (`false`) or exclude (`true`) the criterion.
          # @!attribute [r] type
          #   @return [Google::Ads::GoogleAds::V3::Enums::CriterionTypeEnum::CriterionType]
          #     Output only. The type of the criterion.
          # @!attribute [rw] status
          #   @return [Google::Ads::GoogleAds::V3::Enums::CampaignCriterionStatusEnum::CampaignCriterionStatus]
          #     The status of the criterion.
          # @!attribute [rw] keyword
          #   @return [Google::Ads::GoogleAds::V3::Common::KeywordInfo]
          #     Immutable. Keyword.
          # @!attribute [rw] placement
          #   @return [Google::Ads::GoogleAds::V3::Common::PlacementInfo]
          #     Immutable. Placement.
          # @!attribute [rw] mobile_app_category
          #   @return [Google::Ads::GoogleAds::V3::Common::MobileAppCategoryInfo]
          #     Immutable. Mobile app category.
          # @!attribute [rw] mobile_application
          #   @return [Google::Ads::GoogleAds::V3::Common::MobileApplicationInfo]
          #     Immutable. Mobile application.
          # @!attribute [rw] location
          #   @return [Google::Ads::GoogleAds::V3::Common::LocationInfo]
          #     Immutable. Location.
          # @!attribute [rw] device
          #   @return [Google::Ads::GoogleAds::V3::Common::DeviceInfo]
          #     Immutable. Device.
          # @!attribute [rw] ad_schedule
          #   @return [Google::Ads::GoogleAds::V3::Common::AdScheduleInfo]
          #     Immutable. Ad Schedule.
          # @!attribute [rw] age_range
          #   @return [Google::Ads::GoogleAds::V3::Common::AgeRangeInfo]
          #     Immutable. Age range.
          # @!attribute [rw] gender
          #   @return [Google::Ads::GoogleAds::V3::Common::GenderInfo]
          #     Immutable. Gender.
          # @!attribute [rw] income_range
          #   @return [Google::Ads::GoogleAds::V3::Common::IncomeRangeInfo]
          #     Immutable. Income range.
          # @!attribute [rw] parental_status
          #   @return [Google::Ads::GoogleAds::V3::Common::ParentalStatusInfo]
          #     Immutable. Parental status.
          # @!attribute [rw] user_list
          #   @return [Google::Ads::GoogleAds::V3::Common::UserListInfo]
          #     Immutable. User List.
          # @!attribute [rw] youtube_video
          #   @return [Google::Ads::GoogleAds::V3::Common::YouTubeVideoInfo]
          #     Immutable. YouTube Video.
          # @!attribute [rw] youtube_channel
          #   @return [Google::Ads::GoogleAds::V3::Common::YouTubeChannelInfo]
          #     Immutable. YouTube Channel.
          # @!attribute [rw] proximity
          #   @return [Google::Ads::GoogleAds::V3::Common::ProximityInfo]
          #     Immutable. Proximity.
          # @!attribute [rw] topic
          #   @return [Google::Ads::GoogleAds::V3::Common::TopicInfo]
          #     Immutable. Topic.
          # @!attribute [rw] listing_scope
          #   @return [Google::Ads::GoogleAds::V3::Common::ListingScopeInfo]
          #     Immutable. Listing scope.
          # @!attribute [rw] language
          #   @return [Google::Ads::GoogleAds::V3::Common::LanguageInfo]
          #     Immutable. Language.
          # @!attribute [rw] ip_block
          #   @return [Google::Ads::GoogleAds::V3::Common::IpBlockInfo]
          #     Immutable. IpBlock.
          # @!attribute [rw] content_label
          #   @return [Google::Ads::GoogleAds::V3::Common::ContentLabelInfo]
          #     Immutable. ContentLabel.
          # @!attribute [rw] carrier
          #   @return [Google::Ads::GoogleAds::V3::Common::CarrierInfo]
          #     Immutable. Carrier.
          # @!attribute [rw] user_interest
          #   @return [Google::Ads::GoogleAds::V3::Common::UserInterestInfo]
          #     Immutable. User Interest.
          # @!attribute [rw] webpage
          #   @return [Google::Ads::GoogleAds::V3::Common::WebpageInfo]
          #     Immutable. Webpage.
          # @!attribute [rw] operating_system_version
          #   @return [Google::Ads::GoogleAds::V3::Common::OperatingSystemVersionInfo]
          #     Immutable. Operating system version.
          # @!attribute [rw] mobile_device
          #   @return [Google::Ads::GoogleAds::V3::Common::MobileDeviceInfo]
          #     Immutable. Mobile Device.
          # @!attribute [rw] location_group
          #   @return [Google::Ads::GoogleAds::V3::Common::LocationGroupInfo]
          #     Immutable. Location Group
          # @!attribute [rw] custom_affinity
          #   @return [Google::Ads::GoogleAds::V3::Common::CustomAffinityInfo]
          #     Immutable. Custom Affinity.
          class CampaignCriterion
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
