# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Resources
          # Describes the status of returned resource.
          # @!attribute [r] resource_name
          #   @return [String]
          #     Output only. The resource name of the change status.
          #     Change status resource names have the form:
          #
          #     `customers/{customer_id}/changeStatus/{change_status_id}`
          # @!attribute [r] last_change_date_time
          #   @return [Google::Protobuf::StringValue]
          #     Output only. Time at which the most recent change has occurred on this resource.
          # @!attribute [r] resource_type
          #   @return [Google::Ads::GoogleAds::V3::Enums::ChangeStatusResourceTypeEnum::ChangeStatusResourceType]
          #     Output only. Represents the type of the changed resource. This dictates what fields
          #     will be set. For example, for AD_GROUP, campaign and ad_group fields will
          #     be set.
          # @!attribute [r] campaign
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The Campaign affected by this change.
          # @!attribute [r] ad_group
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The AdGroup affected by this change.
          # @!attribute [r] resource_status
          #   @return [Google::Ads::GoogleAds::V3::Enums::ChangeStatusOperationEnum::ChangeStatusOperation]
          #     Output only. Represents the status of the changed resource.
          # @!attribute [r] ad_group_ad
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The AdGroupAd affected by this change.
          # @!attribute [r] ad_group_criterion
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The AdGroupCriterion affected by this change.
          # @!attribute [r] campaign_criterion
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The CampaignCriterion affected by this change.
          # @!attribute [r] feed
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The Feed affected by this change.
          # @!attribute [r] feed_item
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The FeedItem affected by this change.
          # @!attribute [r] ad_group_feed
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The AdGroupFeed affected by this change.
          # @!attribute [r] campaign_feed
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The CampaignFeed affected by this change.
          # @!attribute [r] ad_group_bid_modifier
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The AdGroupBidModifier affected by this change.
          class ChangeStatus
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
