# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Resources
          # A conversion action.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Immutable. The resource name of the conversion action.
          #     Conversion action resource names have the form:
          #
          #     `customers/{customer_id}/conversionActions/{conversion_action_id}`
          # @!attribute [r] id
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. The ID of the conversion action.
          # @!attribute [rw] name
          #   @return [Google::Protobuf::StringValue]
          #     The name of the conversion action.
          #
          #     This field is required and should not be empty when creating new
          #     conversion actions.
          # @!attribute [rw] status
          #   @return [Google::Ads::GoogleAds::V3::Enums::ConversionActionStatusEnum::ConversionActionStatus]
          #     The status of this conversion action for conversion event accrual.
          # @!attribute [rw] type
          #   @return [Google::Ads::GoogleAds::V3::Enums::ConversionActionTypeEnum::ConversionActionType]
          #     Immutable. The type of this conversion action.
          # @!attribute [rw] category
          #   @return [Google::Ads::GoogleAds::V3::Enums::ConversionActionCategoryEnum::ConversionActionCategory]
          #     The category of conversions reported for this conversion action.
          # @!attribute [r] owner_customer
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The resource name of the conversion action owner customer, or null if this
          #     is a system-defined conversion action.
          # @!attribute [rw] include_in_conversions_metric
          #   @return [Google::Protobuf::BoolValue]
          #     Whether this conversion action should be included in the "conversions"
          #     metric.
          # @!attribute [rw] click_through_lookback_window_days
          #   @return [Google::Protobuf::Int64Value]
          #     The maximum number of days that may elapse between an interaction
          #     (e.g., a click) and a conversion event.
          # @!attribute [rw] view_through_lookback_window_days
          #   @return [Google::Protobuf::Int64Value]
          #     The maximum number of days which may elapse between an impression and a
          #     conversion without an interaction.
          # @!attribute [rw] value_settings
          #   @return [Google::Ads::GoogleAds::V3::Resources::ConversionAction::ValueSettings]
          #     Settings related to the value for conversion events associated with this
          #     conversion action.
          # @!attribute [rw] counting_type
          #   @return [Google::Ads::GoogleAds::V3::Enums::ConversionActionCountingTypeEnum::ConversionActionCountingType]
          #     How to count conversion events for the conversion action.
          # @!attribute [rw] attribution_model_settings
          #   @return [Google::Ads::GoogleAds::V3::Resources::ConversionAction::AttributionModelSettings]
          #     Settings related to this conversion action's attribution model.
          # @!attribute [r] tag_snippets
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::TagSnippet>]
          #     Output only. The snippets used for tracking conversions.
          # @!attribute [rw] phone_call_duration_seconds
          #   @return [Google::Protobuf::Int64Value]
          #     The phone call duration in seconds after which a conversion should be
          #     reported for this conversion action.
          #
          #     The value must be between 0 and 10000, inclusive.
          # @!attribute [rw] app_id
          #   @return [Google::Protobuf::StringValue]
          #     App ID for an app conversion action.
          class ConversionAction
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Settings related to this conversion action's attribution model.
            # @!attribute [rw] attribution_model
            #   @return [Google::Ads::GoogleAds::V3::Enums::AttributionModelEnum::AttributionModel]
            #     The attribution model type of this conversion action.
            # @!attribute [r] data_driven_model_status
            #   @return [Google::Ads::GoogleAds::V3::Enums::DataDrivenModelStatusEnum::DataDrivenModelStatus]
            #     Output only. The status of the data-driven attribution model for the conversion
            #     action.
            class AttributionModelSettings
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end

            # Settings related to the value for conversion events associated with this
            # conversion action.
            # @!attribute [rw] default_value
            #   @return [Google::Protobuf::DoubleValue]
            #     The value to use when conversion events for this conversion action are
            #     sent with an invalid, disallowed or missing value, or when
            #     this conversion action is configured to always use the default value.
            # @!attribute [rw] default_currency_code
            #   @return [Google::Protobuf::StringValue]
            #     The currency code to use when conversion events for this conversion
            #     action are sent with an invalid or missing currency code, or when this
            #     conversion action is configured to always use the default value.
            # @!attribute [rw] always_use_default_value
            #   @return [Google::Protobuf::BoolValue]
            #     Controls whether the default value and default currency code are used in
            #     place of the value and currency code specified in conversion events for
            #     this conversion action.
            class ValueSettings
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end
          end
        end
      end
    end
  end
end
