# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Resources
          # A link between the given customer and a client customer. CustomerClients only
          # exist for manager customers. All direct and indirect client customers are
          # included, as well as the manager itself.
          # @!attribute [r] resource_name
          #   @return [String]
          #     Output only. The resource name of the customer client.
          #     CustomerClient resource names have the form:
          #     `customers/{customer_id}/customerClients/{client_customer_id}`
          # @!attribute [r] client_customer
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The resource name of the client-customer which is linked to
          #     the given customer. Read only.
          # @!attribute [r] hidden
          #   @return [Google::Protobuf::BoolValue]
          #     Output only. Specifies whether this is a
          #     [hidden account](https://support.google.com/google-ads/answer/7519830).
          #     Read only.
          # @!attribute [r] level
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. Distance between given customer and client. For self link, the level value
          #     will be 0. Read only.
          # @!attribute [r] time_zone
          #   @return [Google::Protobuf::StringValue]
          #     Output only. Common Locale Data Repository (CLDR) string representation of the
          #     time zone of the client, e.g. America/Los_Angeles. Read only.
          # @!attribute [r] test_account
          #   @return [Google::Protobuf::BoolValue]
          #     Output only. Identifies if the client is a test account. Read only.
          # @!attribute [r] manager
          #   @return [Google::Protobuf::BoolValue]
          #     Output only. Identifies if the client is a manager. Read only.
          # @!attribute [r] descriptive_name
          #   @return [Google::Protobuf::StringValue]
          #     Output only. Descriptive name for the client. Read only.
          # @!attribute [r] currency_code
          #   @return [Google::Protobuf::StringValue]
          #     Output only. Currency code (e.g. 'USD', 'EUR') for the client. Read only.
          # @!attribute [r] id
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. The ID of the client customer. Read only.
          class CustomerClient
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
