# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Resources
          # A feed item.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Immutable. The resource name of the feed item.
          #     Feed item resource names have the form:
          #
          #     `customers/{customer_id}/feedItems/{feed_id}~{feed_item_id}`
          # @!attribute [rw] feed
          #   @return [Google::Protobuf::StringValue]
          #     Immutable. The feed to which this feed item belongs.
          # @!attribute [r] id
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. The ID of this feed item.
          # @!attribute [rw] start_date_time
          #   @return [Google::Protobuf::StringValue]
          #     Start time in which this feed item is effective and can begin serving. The
          #     time is in the customer's time zone.
          #     The format is "YYYY-MM-DD HH:MM:SS".
          #     Examples: "2018-03-05 09:15:00" or "2018-02-01 14:34:30"
          # @!attribute [rw] end_date_time
          #   @return [Google::Protobuf::StringValue]
          #     End time in which this feed item is no longer effective and will stop
          #     serving. The time is in the customer's time zone.
          #     The format is "YYYY-MM-DD HH:MM:SS".
          #     Examples: "2018-03-05 09:15:00" or "2018-02-01 14:34:30"
          # @!attribute [rw] attribute_values
          #   @return [Array<Google::Ads::GoogleAds::V3::Resources::FeedItemAttributeValue>]
          #     The feed item's attribute values.
          # @!attribute [rw] geo_targeting_restriction
          #   @return [Google::Ads::GoogleAds::V3::Enums::GeoTargetingRestrictionEnum::GeoTargetingRestriction]
          #     Geo targeting restriction specifies the type of location that can be used
          #     for targeting.
          # @!attribute [rw] url_custom_parameters
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::CustomParameter>]
          #     The list of mappings used to substitute custom parameter tags in a
          #     `tracking_url_template`, `final_urls`, or `mobile_final_urls`.
          # @!attribute [r] status
          #   @return [Google::Ads::GoogleAds::V3::Enums::FeedItemStatusEnum::FeedItemStatus]
          #     Output only. Status of the feed item.
          #     This field is read-only.
          # @!attribute [r] policy_infos
          #   @return [Array<Google::Ads::GoogleAds::V3::Resources::FeedItemPlaceholderPolicyInfo>]
          #     Output only. List of info about a feed item's validation and approval state for active
          #     feed mappings. There will be an entry in the list for each type of feed
          #     mapping associated with the feed, e.g. a feed with a sitelink and a call
          #     feed mapping would cause every feed item associated with that feed to have
          #     an entry in this list for both sitelink and call.
          #     This field is read-only.
          class FeedItem
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A feed item attribute value.
          # @!attribute [rw] feed_attribute_id
          #   @return [Google::Protobuf::Int64Value]
          #     Id of the feed attribute for which the value is associated with.
          # @!attribute [rw] integer_value
          #   @return [Google::Protobuf::Int64Value]
          #     Int64 value. Should be set if feed_attribute_id refers to a feed attribute
          #     of type INT64.
          # @!attribute [rw] boolean_value
          #   @return [Google::Protobuf::BoolValue]
          #     Bool value. Should be set if feed_attribute_id refers to a feed attribute
          #     of type BOOLEAN.
          # @!attribute [rw] string_value
          #   @return [Google::Protobuf::StringValue]
          #     String value. Should be set if feed_attribute_id refers to a feed attribute
          #     of type STRING, URL or DATE_TIME.
          #     For STRING the maximum length is 1500 characters. For URL the maximum
          #     length is 2076 characters. For DATE_TIME the string must be in the format
          #     "YYYYMMDD HHMMSS".
          # @!attribute [rw] double_value
          #   @return [Google::Protobuf::DoubleValue]
          #     Double value. Should be set if feed_attribute_id refers to a feed attribute
          #     of type DOUBLE.
          # @!attribute [rw] price_value
          #   @return [Google::Ads::GoogleAds::V3::Common::Money]
          #     Price value. Should be set if feed_attribute_id refers to a feed attribute
          #     of type PRICE.
          # @!attribute [rw] integer_values
          #   @return [Array<Google::Protobuf::Int64Value>]
          #     Repeated int64 value. Should be set if feed_attribute_id refers to a feed
          #     attribute of type INT64_LIST.
          # @!attribute [rw] boolean_values
          #   @return [Array<Google::Protobuf::BoolValue>]
          #     Repeated bool value. Should be set if feed_attribute_id refers to a feed
          #     attribute of type BOOLEAN_LIST.
          # @!attribute [rw] string_values
          #   @return [Array<Google::Protobuf::StringValue>]
          #     Repeated string value. Should be set if feed_attribute_id refers to a feed
          #     attribute of type STRING_LIST, URL_LIST or DATE_TIME_LIST.
          #     For STRING_LIST and URL_LIST the total size of the list in bytes may not
          #     exceed 3000. For DATE_TIME_LIST the number of elements may not exceed 200.
          #
          #     For STRING_LIST the maximum length of each string element is 1500
          #     characters. For URL_LIST the maximum length is 2076 characters. For
          #     DATE_TIME the format of the string must be the same as start and end time
          #     for the feed item.
          # @!attribute [rw] double_values
          #   @return [Array<Google::Protobuf::DoubleValue>]
          #     Repeated double value. Should be set if feed_attribute_id refers to a feed
          #     attribute of type DOUBLE_LIST.
          class FeedItemAttributeValue
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Policy, validation, and quality approval info for a feed item for the
          # specified placeholder type.
          # @!attribute [r] placeholder_type_enum
          #   @return [Google::Ads::GoogleAds::V3::Enums::PlaceholderTypeEnum::PlaceholderType]
          #     Output only. The placeholder type.
          # @!attribute [r] feed_mapping_resource_name
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The FeedMapping that contains the placeholder type.
          # @!attribute [r] review_status
          #   @return [Google::Ads::GoogleAds::V3::Enums::PolicyReviewStatusEnum::PolicyReviewStatus]
          #     Output only. Where the placeholder type is in the review process.
          # @!attribute [r] approval_status
          #   @return [Google::Ads::GoogleAds::V3::Enums::PolicyApprovalStatusEnum::PolicyApprovalStatus]
          #     Output only. The overall approval status of the placeholder type, calculated based on
          #     the status of its individual policy topic entries.
          # @!attribute [r] policy_topic_entries
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::PolicyTopicEntry>]
          #     Output only. The list of policy findings for the placeholder type.
          # @!attribute [r] validation_status
          #   @return [Google::Ads::GoogleAds::V3::Enums::FeedItemValidationStatusEnum::FeedItemValidationStatus]
          #     Output only. The validation status of the palceholder type.
          # @!attribute [r] validation_errors
          #   @return [Array<Google::Ads::GoogleAds::V3::Resources::FeedItemValidationError>]
          #     Output only. List of placeholder type validation errors.
          # @!attribute [r] quality_approval_status
          #   @return [Google::Ads::GoogleAds::V3::Enums::FeedItemQualityApprovalStatusEnum::FeedItemQualityApprovalStatus]
          #     Output only. Placeholder type quality evaluation approval status.
          # @!attribute [r] quality_disapproval_reasons
          #   @return [Array<Google::Ads::GoogleAds::V3::Enums::FeedItemQualityDisapprovalReasonEnum::FeedItemQualityDisapprovalReason>]
          #     Output only. List of placeholder type quality evaluation disapproval reasons.
          class FeedItemPlaceholderPolicyInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Stores a validation error and the set of offending feed attributes which
          # together are responsible for causing a feed item validation error.
          # @!attribute [r] validation_error
          #   @return [Google::Ads::GoogleAds::V3::Errors::FeedItemValidationErrorEnum::FeedItemValidationError]
          #     Output only. Error code indicating what validation error was triggered. The description
          #     of the error can be found in the 'description' field.
          # @!attribute [r] description
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The description of the validation error.
          # @!attribute [r] feed_attribute_ids
          #   @return [Array<Google::Protobuf::Int64Value>]
          #     Output only. Set of feed attributes in the feed item flagged during validation. If
          #     empty, no specific feed attributes can be associated with the error
          #     (e.g. error across the entire feed item).
          # @!attribute [r] extra_info
          #   @return [Google::Protobuf::StringValue]
          #     Output only. Any extra information related to this error which is not captured by
          #     validation_error and feed_attribute_id (e.g. placeholder field IDs when
          #     feed_attribute_id is not mapped). Note that extra_info is not localized.
          class FeedItemValidationError
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
