# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Resources
          # An invoice. All invoice information is snapshotted to match the PDF invoice.
          # For invoices older than the launch of InvoiceService, the snapshotted
          # information may not match the PDF invoice.
          # @!attribute [r] resource_name
          #   @return [String]
          #     Output only. The resource name of the invoice. Multiple customers can share a given
          #     invoice, so multiple resource names may point to the same invoice.
          #     Invoice resource names have the form:
          #
          #     `customers/{customer_id}/invoices/{invoice_id}`
          # @!attribute [r] id
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The ID of the invoice. It appears on the invoice PDF as "Invoice number".
          # @!attribute [r] type
          #   @return [Google::Ads::GoogleAds::V3::Enums::InvoiceTypeEnum::InvoiceType]
          #     Output only. The type of invoice.
          # @!attribute [r] billing_setup
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The resource name of this invoice’s billing setup.
          #
          #     `customers/{customer_id}/billingSetups/{billing_setup_id}`
          # @!attribute [r] payments_account_id
          #   @return [Google::Protobuf::StringValue]
          #     Output only. A 16 digit ID used to identify the payments account associated with the
          #     billing setup, e.g. "1234-5678-9012-3456". It appears on the invoice PDF as
          #     "Billing Account Number".
          # @!attribute [r] payments_profile_id
          #   @return [Google::Protobuf::StringValue]
          #     Output only. A 12 digit ID used to identify the payments profile associated with the
          #     billing setup, e.g. "1234-5678-9012". It appears on the invoice PDF as
          #     "Billing ID".
          # @!attribute [r] issue_date
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The issue date in yyyy-mm-dd format. It appears on the invoice PDF as
          #     either "Issue date" or "Invoice date".
          # @!attribute [r] due_date
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The due date in yyyy-mm-dd format.
          # @!attribute [r] service_date_range
          #   @return [Google::Ads::GoogleAds::V3::Common::DateRange]
          #     Output only. The service period date range of this invoice. The end date is inclusive.
          # @!attribute [r] currency_code
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The currency code. All costs are returned in this currency. A subset of the
          #     currency codes derived from the ISO 4217 standard is supported.
          # @!attribute [r] invoice_level_adjustments_micros
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. The total amount of invoice level adjustments. These adjustments are made
          #     on the invoice, not on a specific account budget.
          # @!attribute [r] subtotal_amount_micros
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. The pretax subtotal amount, in micros. This equals the sum of the
          #     AccountBudgetSummary subtotal amounts, plus the invoice level adjustments.
          # @!attribute [r] tax_amount_micros
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. The sum of all taxes on the invoice, in micros. This equals the sum of the
          #     AccountBudgetSummary tax amounts, plus taxes not associated with a specific
          #     account budget.
          # @!attribute [r] total_amount_micros
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. The total amount, in micros. This equals the sum of the invoice subtotal
          #     amount and the invoice tax amount.
          # @!attribute [r] corrected_invoice
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The resource name of the original invoice corrected, wrote off, or canceled
          #     by this invoice, if applicable. If `corrected_invoice` is set,
          #     `replaced_invoices` will not be set.
          #
          #     Invoice resource names have the form:
          #
          #     `customers/{customer_id}/invoices/{invoice_id}`
          # @!attribute [r] replaced_invoices
          #   @return [Array<Google::Protobuf::StringValue>]
          #     Output only. The resource name of the original invoice(s) being rebilled or replaced by
          #     this invoice, if applicable. There might be multiple replaced invoices due
          #     to invoice consolidation. The replaced invoices may not belong to the same
          #     payments account. If `replaced_invoices` is set, `corrected_invoice` will
          #     not be set.
          #     Invoice resource names have the form:
          #
          #     `customers/{customer_id}/invoices/{invoice_id}`
          # @!attribute [r] pdf_url
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The URL to a PDF copy of the invoice. Users need to pass in their OAuth
          #     token to request the PDF with this URL.
          # @!attribute [r] account_budget_summaries
          #   @return [Array<Google::Ads::GoogleAds::V3::Resources::Invoice::AccountBudgetSummary>]
          #     Output only. The list of summarized account budget information associated with this
          #     invoice.
          class Invoice
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Represents a summarized account budget billable cost.
            # @!attribute [r] customer
            #   @return [Google::Protobuf::StringValue]
            #     Output only. The resource name of the customer associated with this account budget.
            #     This contains the customer ID, which appears on the invoice PDF as
            #     "Account ID".
            #     Customer resource names have the form:
            #
            #     `customers/{customer_id}`
            # @!attribute [r] customer_descriptive_name
            #   @return [Google::Protobuf::StringValue]
            #     Output only. The descriptive name of the account budget’s customer. It appears on the
            #     invoice PDF as "Account".
            # @!attribute [r] account_budget
            #   @return [Google::Protobuf::StringValue]
            #     Output only. The resource name of the account budget associated with this summarized
            #     billable cost.
            #     AccountBudget resource names have the form:
            #
            #     `customers/{customer_id}/accountBudgets/{account_budget_id}`
            # @!attribute [r] account_budget_name
            #   @return [Google::Protobuf::StringValue]
            #     Output only. The name of the account budget. It appears on the invoice PDF as "Account
            #     budget".
            # @!attribute [r] purchase_order_number
            #   @return [Google::Protobuf::StringValue]
            #     Output only. The purchase order number of the account budget. It appears on the
            #     invoice PDF as "Purchase order".
            # @!attribute [r] subtotal_amount_micros
            #   @return [Google::Protobuf::Int64Value]
            #     Output only. The pretax subtotal amount attributable to this budget during the service
            #     period, in micros.
            # @!attribute [r] tax_amount_micros
            #   @return [Google::Protobuf::Int64Value]
            #     Output only. The tax amount attributable to this budget during the service period, in
            #     micros.
            # @!attribute [r] total_amount_micros
            #   @return [Google::Protobuf::Int64Value]
            #     Output only. The total amount attributable to this budget during the service period,
            #     in micros. This equals the sum of the account budget subtotal amount and
            #     the account budget tax amount.
            # @!attribute [r] billable_activity_date_range
            #   @return [Google::Ads::GoogleAds::V3::Common::DateRange]
            #     Output only. The billable activity date range of the account budget, within the
            #     service date range of this invoice. The end date is inclusive. This can
            #     be different from the account budget's start and end time.
            class AccountBudgetSummary
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end
          end
        end
      end
    end
  end
end
