# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Resources
          # A Keyword Planner ad group.
          # Max number of keyword plan ad groups per plan: 200.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Immutable. The resource name of the Keyword Planner ad group.
          #     KeywordPlanAdGroup resource names have the form:
          #
          #     `customers/{customer_id}/keywordPlanAdGroups/{kp_ad_group_id}`
          # @!attribute [rw] keyword_plan_campaign
          #   @return [Google::Protobuf::StringValue]
          #     The keyword plan campaign to which this ad group belongs.
          # @!attribute [r] id
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. The ID of the keyword plan ad group.
          # @!attribute [rw] name
          #   @return [Google::Protobuf::StringValue]
          #     The name of the keyword plan ad group.
          #
          #     This field is required and should not be empty when creating keyword plan
          #     ad group.
          # @!attribute [rw] cpc_bid_micros
          #   @return [Google::Protobuf::Int64Value]
          #     A default ad group max cpc bid in micros in account currency for all
          #     biddable keywords under the keyword plan ad group.
          #     If not set, will inherit from parent campaign.
          class KeywordPlanAdGroup
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
