# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Resources
          # A Product Bidding Category.
          # @!attribute [r] resource_name
          #   @return [String]
          #     Output only. The resource name of the product bidding category.
          #     Product bidding category resource names have the form:
          #
          #     `productBiddingCategoryConstants/{country_code}~{level}~{id}`
          # @!attribute [r] id
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. ID of the product bidding category.
          #
          #     This ID is equivalent to the google_product_category ID as described in
          #     this article: https://support.google.com/merchants/answer/6324436.
          # @!attribute [r] country_code
          #   @return [Google::Protobuf::StringValue]
          #     Output only. Two-letter upper-case country code of the product bidding category.
          # @!attribute [r] product_bidding_category_constant_parent
          #   @return [Google::Protobuf::StringValue]
          #     Output only. Resource name of the parent product bidding category.
          # @!attribute [r] level
          #   @return [Google::Ads::GoogleAds::V3::Enums::ProductBiddingCategoryLevelEnum::ProductBiddingCategoryLevel]
          #     Output only. Level of the product bidding category.
          # @!attribute [r] status
          #   @return [Google::Ads::GoogleAds::V3::Enums::ProductBiddingCategoryStatusEnum::ProductBiddingCategoryStatus]
          #     Output only. Status of the product bidding category.
          # @!attribute [r] language_code
          #   @return [Google::Protobuf::StringValue]
          #     Output only. Language code of the product bidding category.
          # @!attribute [r] localized_name
          #   @return [Google::Protobuf::StringValue]
          #     Output only. Display value of the product bidding category localized according to
          #     language_code.
          class ProductBiddingCategoryConstant
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
