# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Resources
          # A user list. This is a list of users a customer may target.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Immutable. The resource name of the user list.
          #     User list resource names have the form:
          #
          #     `customers/{customer_id}/userLists/{user_list_id}`
          # @!attribute [r] id
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. Id of the user list.
          # @!attribute [r] read_only
          #   @return [Google::Protobuf::BoolValue]
          #     Output only. A flag that indicates if a user may edit a list. Depends on the list
          #     ownership and list type. For example, external remarketing user lists are
          #     not editable.
          #
          #     This field is read-only.
          # @!attribute [rw] name
          #   @return [Google::Protobuf::StringValue]
          #     Name of this user list. Depending on its access_reason, the user list name
          #     may not be unique (e.g. if access_reason=SHARED)
          # @!attribute [rw] description
          #   @return [Google::Protobuf::StringValue]
          #     Description of this user list.
          # @!attribute [rw] membership_status
          #   @return [Google::Ads::GoogleAds::V3::Enums::UserListMembershipStatusEnum::UserListMembershipStatus]
          #     Membership status of this user list. Indicates whether a user list is open
          #     or active. Only open user lists can accumulate more users and can be
          #     targeted to.
          # @!attribute [rw] integration_code
          #   @return [Google::Protobuf::StringValue]
          #     An ID from external system. It is used by user list sellers to correlate
          #     IDs on their systems.
          # @!attribute [rw] membership_life_span
          #   @return [Google::Protobuf::Int64Value]
          #     Number of days a user's cookie stays on your list since its most recent
          #     addition to the list. This field must be between 0 and 540 inclusive.
          #     However, for CRM based userlists, this field can be set to 10000 which
          #     means no expiration.
          #
          #     It'll be ignored for logical_user_list.
          # @!attribute [r] size_for_display
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. Estimated number of users in this user list, on the Google Display Network.
          #     This value is null if the number of users has not yet been determined.
          #
          #     This field is read-only.
          # @!attribute [r] size_range_for_display
          #   @return [Google::Ads::GoogleAds::V3::Enums::UserListSizeRangeEnum::UserListSizeRange]
          #     Output only. Size range in terms of number of users of the UserList, on the Google
          #     Display Network.
          #
          #     This field is read-only.
          # @!attribute [r] size_for_search
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. Estimated number of users in this user list in the google.com domain.
          #     These are the users available for targeting in Search campaigns.
          #     This value is null if the number of users has not yet been determined.
          #
          #     This field is read-only.
          # @!attribute [r] size_range_for_search
          #   @return [Google::Ads::GoogleAds::V3::Enums::UserListSizeRangeEnum::UserListSizeRange]
          #     Output only. Size range in terms of number of users of the UserList, for Search ads.
          #
          #     This field is read-only.
          # @!attribute [r] type
          #   @return [Google::Ads::GoogleAds::V3::Enums::UserListTypeEnum::UserListType]
          #     Output only. Type of this list.
          #
          #     This field is read-only.
          # @!attribute [rw] closing_reason
          #   @return [Google::Ads::GoogleAds::V3::Enums::UserListClosingReasonEnum::UserListClosingReason]
          #     Indicating the reason why this user list membership status is closed. It is
          #     only populated on lists that were automatically closed due to inactivity,
          #     and will be cleared once the list membership status becomes open.
          # @!attribute [r] access_reason
          #   @return [Google::Ads::GoogleAds::V3::Enums::AccessReasonEnum::AccessReason]
          #     Output only. Indicates the reason this account has been granted access to the list.
          #     The reason can be SHARED, OWNED, LICENSED or SUBSCRIBED.
          #
          #     This field is read-only.
          # @!attribute [rw] account_user_list_status
          #   @return [Google::Ads::GoogleAds::V3::Enums::UserListAccessStatusEnum::UserListAccessStatus]
          #     Indicates if this share is still enabled. When a UserList is shared with
          #     the user this field is set to ENABLED. Later the userList owner can decide
          #     to revoke the share and make it DISABLED.
          #     The default value of this field is set to ENABLED.
          # @!attribute [rw] eligible_for_search
          #   @return [Google::Protobuf::BoolValue]
          #     Indicates if this user list is eligible for Google Search Network.
          # @!attribute [r] eligible_for_display
          #   @return [Google::Protobuf::BoolValue]
          #     Output only. Indicates this user list is eligible for Google Display Network.
          #
          #     This field is read-only.
          # @!attribute [rw] crm_based_user_list
          #   @return [Google::Ads::GoogleAds::V3::Common::CrmBasedUserListInfo]
          #     User list of CRM users provided by the advertiser.
          # @!attribute [r] similar_user_list
          #   @return [Google::Ads::GoogleAds::V3::Common::SimilarUserListInfo]
          #     Output only. User list which are similar to users from another UserList.
          #     These lists are readonly and automatically created by google.
          # @!attribute [rw] rule_based_user_list
          #   @return [Google::Ads::GoogleAds::V3::Common::RuleBasedUserListInfo]
          #     User list generated by a rule.
          # @!attribute [rw] logical_user_list
          #   @return [Google::Ads::GoogleAds::V3::Common::LogicalUserListInfo]
          #     User list that is a custom combination of user lists and user interests.
          # @!attribute [rw] basic_user_list
          #   @return [Google::Ads::GoogleAds::V3::Common::BasicUserListInfo]
          #     User list targeting as a collection of conversion or remarketing actions.
          class UserList
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
