# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: regapic/regapic.proto for package 'testing.regapic'

require 'grpc'
require 'regapic/regapic_pb'

module Testing
  module Regapic
    module ServiceTranscoding
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'testing.regapic.ServiceTranscoding'

        rpc :PlainNoTemplate, ::Testing::Regapic::Request, ::Testing::Regapic::Response
        rpc :Plain, ::Testing::Regapic::Request, ::Testing::Regapic::Response
        rpc :WithSubMessage, ::Testing::Regapic::Request, ::Testing::Regapic::Response
        rpc :WithMultipleLevels, ::Testing::Regapic::Request, ::Testing::Regapic::Response
        rpc :WithAdditionalBindings, ::Testing::Regapic::Request, ::Testing::Regapic::Response
      end

      Stub = Service.rpc_stub_class
    end
  end
end
