# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Common
          # A text ad.
          # @!attribute [rw] headline
          #   @return [Google::Protobuf::StringValue]
          #     The headline of the ad.
          # @!attribute [rw] description1
          #   @return [Google::Protobuf::StringValue]
          #     The first line of the ad's description.
          # @!attribute [rw] description2
          #   @return [Google::Protobuf::StringValue]
          #     The second line of the ad's description.
          class TextAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # An expanded text ad.
          # @!attribute [rw] headline_part1
          #   @return [Google::Protobuf::StringValue]
          #     The first part of the ad's headline.
          # @!attribute [rw] headline_part2
          #   @return [Google::Protobuf::StringValue]
          #     The second part of the ad's headline.
          # @!attribute [rw] headline_part3
          #   @return [Google::Protobuf::StringValue]
          #     The third part of the ad's headline.
          # @!attribute [rw] description
          #   @return [Google::Protobuf::StringValue]
          #     The description of the ad.
          # @!attribute [rw] description2
          #   @return [Google::Protobuf::StringValue]
          #     The second description of the ad.
          # @!attribute [rw] path1
          #   @return [Google::Protobuf::StringValue]
          #     The text that can appear alongside the ad's displayed URL.
          # @!attribute [rw] path2
          #   @return [Google::Protobuf::StringValue]
          #     Additional text that can appear alongside the ad's displayed URL.
          class ExpandedTextAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A call-only ad.
          # @!attribute [rw] country_code
          #   @return [Google::Protobuf::StringValue]
          #     The country code in the ad.
          # @!attribute [rw] phone_number
          #   @return [Google::Protobuf::StringValue]
          #     The phone number in the ad.
          # @!attribute [rw] business_name
          #   @return [Google::Protobuf::StringValue]
          #     The business name in the ad.
          # @!attribute [rw] headline1
          #   @return [Google::Protobuf::StringValue]
          #     First headline in the ad.
          # @!attribute [rw] headline2
          #   @return [Google::Protobuf::StringValue]
          #     Second headline in the ad.
          # @!attribute [rw] description1
          #   @return [Google::Protobuf::StringValue]
          #     The first line of the ad's description.
          # @!attribute [rw] description2
          #   @return [Google::Protobuf::StringValue]
          #     The second line of the ad's description.
          # @!attribute [rw] call_tracked
          #   @return [Google::Protobuf::BoolValue]
          #     Whether to enable call tracking for the creative. Enabling call
          #     tracking also enables call conversions.
          # @!attribute [rw] disable_call_conversion
          #   @return [Google::Protobuf::BoolValue]
          #     Whether to disable call conversion for the creative.
          #     If set to `true`, disables call conversions even when `call_tracked` is
          #     `true`.
          #     If `call_tracked` is `false`, this field is ignored.
          # @!attribute [rw] phone_number_verification_url
          #   @return [Google::Protobuf::StringValue]
          #     The URL to be used for phone number verification.
          # @!attribute [rw] conversion_action
          #   @return [Google::Protobuf::StringValue]
          #     The conversion action to attribute a call conversion to. If not set a
          #     default conversion action is used. This field only has effect if
          #     call_tracked is set to true. Otherwise this field is ignored.
          # @!attribute [rw] conversion_reporting_state
          #   @return [Google::Ads::GoogleAds::V3::Enums::CallConversionReportingStateEnum::CallConversionReportingState]
          #     The call conversion behavior of this call only ad. It can use its own call
          #     conversion setting, inherit the account level setting, or be disabled.
          class CallOnlyAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # An expanded dynamic search ad.
          # @!attribute [rw] description
          #   @return [Google::Protobuf::StringValue]
          #     The description of the ad.
          # @!attribute [rw] description2
          #   @return [Google::Protobuf::StringValue]
          #     The second description of the ad.
          class ExpandedDynamicSearchAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A hotel ad.
          class HotelAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A Smart Shopping ad.
          class ShoppingSmartAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A standard Shopping ad.
          class ShoppingProductAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A Shopping Comparison Listing ad.
          # @!attribute [rw] headline
          #   @return [Google::Protobuf::StringValue]
          #     Headline of the ad. This field is required. Allowed length is between 25
          #     and 45 characters.
          class ShoppingComparisonListingAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A Gmail ad.
          # @!attribute [rw] teaser
          #   @return [Google::Ads::GoogleAds::V3::Common::GmailTeaser]
          #     The Gmail teaser.
          # @!attribute [rw] header_image
          #   @return [Google::Protobuf::StringValue]
          #     The MediaFile resource name of the header image. Valid image types are GIF,
          #     JPEG and PNG. The minimum size is 300x100 pixels and the aspect ratio must
          #     be between 3:1 and 5:1 (+-1%).
          # @!attribute [rw] marketing_image
          #   @return [Google::Protobuf::StringValue]
          #     The MediaFile resource name of the marketing image. Valid image types are
          #     GIF, JPEG and PNG. The image must either be landscape with a minimum size
          #     of 600x314 pixels and aspect ratio of 600:314 (+-1%) or square with a
          #     minimum size of 300x300 pixels and aspect ratio of 1:1 (+-1%)
          # @!attribute [rw] marketing_image_headline
          #   @return [Google::Protobuf::StringValue]
          #     Headline of the marketing image.
          # @!attribute [rw] marketing_image_description
          #   @return [Google::Protobuf::StringValue]
          #     Description of the marketing image.
          # @!attribute [rw] marketing_image_display_call_to_action
          #   @return [Google::Ads::GoogleAds::V3::Common::DisplayCallToAction]
          #     Display-call-to-action of the marketing image.
          # @!attribute [rw] product_images
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::ProductImage>]
          #     Product images. Up to 15 images are supported.
          # @!attribute [rw] product_videos
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::ProductVideo>]
          #     Product videos. Up to 7 videos are supported. At least one product video
          #     or a marketing image must be specified.
          class GmailAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Gmail teaser data. The teaser is a small header that acts as an invitation
          # to view the rest of the ad (the body).
          # @!attribute [rw] headline
          #   @return [Google::Protobuf::StringValue]
          #     Headline of the teaser.
          # @!attribute [rw] description
          #   @return [Google::Protobuf::StringValue]
          #     Description of the teaser.
          # @!attribute [rw] business_name
          #   @return [Google::Protobuf::StringValue]
          #     Business name of the advertiser.
          # @!attribute [rw] logo_image
          #   @return [Google::Protobuf::StringValue]
          #     The MediaFile resource name of the logo image. Valid image types are GIF,
          #     JPEG and PNG. The minimum size is 144x144 pixels and the aspect ratio must
          #     be 1:1 (+-1%).
          class GmailTeaser
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Data for display call to action. The call to action is a piece of the ad
          # that prompts the user to do something. Like clicking a link or making a phone
          # call.
          # @!attribute [rw] text
          #   @return [Google::Protobuf::StringValue]
          #     Text for the display-call-to-action.
          # @!attribute [rw] text_color
          #   @return [Google::Protobuf::StringValue]
          #     Text color for the display-call-to-action in hexadecimal, e.g. #ffffff for
          #     white.
          # @!attribute [rw] url_collection_id
          #   @return [Google::Protobuf::StringValue]
          #     Identifies the url collection in the ad.url_collections field. If not set
          #     the url defaults to final_url.
          class DisplayCallToAction
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Product image specific data.
          # @!attribute [rw] product_image
          #   @return [Google::Protobuf::StringValue]
          #     The MediaFile resource name of the product image. Valid image types are
          #     GIF, JPEG and PNG. The minimum size is 300x300 pixels and the aspect ratio
          #     must be 1:1 (+-1%).
          # @!attribute [rw] description
          #   @return [Google::Protobuf::StringValue]
          #     Description of the product.
          # @!attribute [rw] display_call_to_action
          #   @return [Google::Ads::GoogleAds::V3::Common::DisplayCallToAction]
          #     Display-call-to-action of the product image.
          class ProductImage
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Product video specific data.
          # @!attribute [rw] product_video
          #   @return [Google::Protobuf::StringValue]
          #     The MediaFile resource name of a video which must be hosted on YouTube.
          class ProductVideo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # An image ad.
          # @!attribute [rw] pixel_width
          #   @return [Google::Protobuf::Int64Value]
          #     Width in pixels of the full size image.
          # @!attribute [rw] pixel_height
          #   @return [Google::Protobuf::Int64Value]
          #     Height in pixels of the full size image.
          # @!attribute [rw] image_url
          #   @return [Google::Protobuf::StringValue]
          #     URL of the full size image.
          # @!attribute [rw] preview_pixel_width
          #   @return [Google::Protobuf::Int64Value]
          #     Width in pixels of the preview size image.
          # @!attribute [rw] preview_pixel_height
          #   @return [Google::Protobuf::Int64Value]
          #     Height in pixels of the preview size image.
          # @!attribute [rw] preview_image_url
          #   @return [Google::Protobuf::StringValue]
          #     URL of the preview size image.
          # @!attribute [rw] mime_type
          #   @return [Google::Ads::GoogleAds::V3::Enums::MimeTypeEnum::MimeType]
          #     The mime type of the image.
          # @!attribute [rw] name
          #   @return [Google::Protobuf::StringValue]
          #     The name of the image. If the image was created from a MediaFile, this is
          #     the MediaFile's name. If the image was created from bytes, this is empty.
          # @!attribute [rw] media_file
          #   @return [Google::Protobuf::StringValue]
          #     The MediaFile resource to use for the image.
          # @!attribute [rw] data
          #   @return [Google::Protobuf::BytesValue]
          #     Raw image data as bytes.
          # @!attribute [rw] ad_id_to_copy_image_from
          #   @return [Google::Protobuf::Int64Value]
          #     An ad ID to copy the image from.
          class ImageAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Representation of video bumper in-stream ad format (very short in-stream
          # non-skippable video ad).
          # @!attribute [rw] companion_banner
          #   @return [Google::Protobuf::StringValue]
          #     The MediaFile resource name of the companion banner used with the ad.
          class VideoBumperInStreamAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Representation of video non-skippable in-stream ad format (15 second
          # in-stream non-skippable video ad).
          # @!attribute [rw] companion_banner
          #   @return [Google::Protobuf::StringValue]
          #     The MediaFile resource name of the companion banner used with the ad.
          class VideoNonSkippableInStreamAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Representation of video TrueView in-stream ad format (ad shown during video
          # playback, often at beginning, which displays a skip button a few seconds into
          # the video).
          # @!attribute [rw] action_button_label
          #   @return [Google::Protobuf::StringValue]
          #     Label on the CTA (call-to-action) button taking the user to the video ad's
          #     final URL.
          #     Required for TrueView for action campaigns, optional otherwise.
          # @!attribute [rw] action_headline
          #   @return [Google::Protobuf::StringValue]
          #     Additional text displayed with the CTA (call-to-action) button to give
          #     context and encourage clicking on the button.
          # @!attribute [rw] companion_banner
          #   @return [Google::Protobuf::StringValue]
          #     The MediaFile resource name of the companion banner used with the ad.
          class VideoTrueViewInStreamAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Representation of video out-stream ad format (ad shown alongside a feed
          # with automatic playback, without sound).
          # @!attribute [rw] headline
          #   @return [Google::Protobuf::StringValue]
          #     The headline of the ad.
          # @!attribute [rw] description
          #   @return [Google::Protobuf::StringValue]
          #     The description line.
          class VideoOutstreamAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Representation of video TrueView discovery ad format.
          # @!attribute [rw] headline
          #   @return [Google::Protobuf::StringValue]
          #     The headline of the ad.
          # @!attribute [rw] description1
          #   @return [Google::Protobuf::StringValue]
          #     First text line for a TrueView video discovery ad.
          # @!attribute [rw] description2
          #   @return [Google::Protobuf::StringValue]
          #     Second text line for a TrueView video discovery ad.
          class VideoTrueViewDiscoveryAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A video ad.
          # @!attribute [rw] media_file
          #   @return [Google::Protobuf::StringValue]
          #     The MediaFile resource to use for the video.
          # @!attribute [rw] in_stream
          #   @return [Google::Ads::GoogleAds::V3::Common::VideoTrueViewInStreamAdInfo]
          #     Video TrueView in-stream ad format.
          # @!attribute [rw] bumper
          #   @return [Google::Ads::GoogleAds::V3::Common::VideoBumperInStreamAdInfo]
          #     Video bumper in-stream ad format.
          # @!attribute [rw] out_stream
          #   @return [Google::Ads::GoogleAds::V3::Common::VideoOutstreamAdInfo]
          #     Video out-stream ad format.
          # @!attribute [rw] non_skippable
          #   @return [Google::Ads::GoogleAds::V3::Common::VideoNonSkippableInStreamAdInfo]
          #     Video non-skippable in-stream ad format.
          # @!attribute [rw] discovery
          #   @return [Google::Ads::GoogleAds::V3::Common::VideoTrueViewDiscoveryAdInfo]
          #     Video TrueView discovery ad format.
          class VideoAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A responsive search ad.
          #
          # Responsive search ads let you create an ad that adapts to show more text, and
          # more relevant messages, to your customers. Enter multiple headlines and
          # descriptions when creating a responsive search ad, and over time, Google Ads
          # will automatically test different combinations and learn which combinations
          # perform best. By adapting your ad's content to more closely match potential
          # customers' search terms, responsive search ads may improve your campaign's
          # performance.
          #
          # More information at https://support.google.com/google-ads/answer/7684791
          # @!attribute [rw] headlines
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdTextAsset>]
          #     List of text assets for headlines. When the ad serves the headlines will
          #     be selected from this list.
          # @!attribute [rw] descriptions
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdTextAsset>]
          #     List of text assets for descriptions. When the ad serves the descriptions
          #     will be selected from this list.
          # @!attribute [rw] path1
          #   @return [Google::Protobuf::StringValue]
          #     First part of text that may appear appended to the url displayed in the ad.
          # @!attribute [rw] path2
          #   @return [Google::Protobuf::StringValue]
          #     Second part of text that may appear appended to the url displayed in the
          #     ad. This field can only be set when path1 is also set.
          class ResponsiveSearchAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A legacy responsive display ad. Ads of this type are labeled 'Responsive ads'
          # in the Google Ads UI.
          # @!attribute [rw] short_headline
          #   @return [Google::Protobuf::StringValue]
          #     The short version of the ad's headline.
          # @!attribute [rw] long_headline
          #   @return [Google::Protobuf::StringValue]
          #     The long version of the ad's headline.
          # @!attribute [rw] description
          #   @return [Google::Protobuf::StringValue]
          #     The description of the ad.
          # @!attribute [rw] business_name
          #   @return [Google::Protobuf::StringValue]
          #     The business name in the ad.
          # @!attribute [rw] allow_flexible_color
          #   @return [Google::Protobuf::BoolValue]
          #     Advertiser's consent to allow flexible color. When true, the ad may be
          #     served with different color if necessary. When false, the ad will be served
          #     with the specified colors or a neutral color.
          #     The default value is true.
          #     Must be true if main_color and accent_color are not set.
          # @!attribute [rw] accent_color
          #   @return [Google::Protobuf::StringValue]
          #     The accent color of the ad in hexadecimal, e.g. #ffffff for white.
          #     If one of main_color and accent_color is set, the other is required as
          #     well.
          # @!attribute [rw] main_color
          #   @return [Google::Protobuf::StringValue]
          #     The main color of the ad in hexadecimal, e.g. #ffffff for white.
          #     If one of main_color and accent_color is set, the other is required as
          #     well.
          # @!attribute [rw] call_to_action_text
          #   @return [Google::Protobuf::StringValue]
          #     The call-to-action text for the ad.
          # @!attribute [rw] logo_image
          #   @return [Google::Protobuf::StringValue]
          #     The MediaFile resource name of the logo image used in the ad.
          # @!attribute [rw] square_logo_image
          #   @return [Google::Protobuf::StringValue]
          #     The MediaFile resource name of the square logo image used in the ad.
          # @!attribute [rw] marketing_image
          #   @return [Google::Protobuf::StringValue]
          #     The MediaFile resource name of the marketing image used in the ad.
          # @!attribute [rw] square_marketing_image
          #   @return [Google::Protobuf::StringValue]
          #     The MediaFile resource name of the square marketing image used in the ad.
          # @!attribute [rw] format_setting
          #   @return [Google::Ads::GoogleAds::V3::Enums::DisplayAdFormatSettingEnum::DisplayAdFormatSetting]
          #     Specifies which format the ad will be served in. Default is ALL_FORMATS.
          # @!attribute [rw] price_prefix
          #   @return [Google::Protobuf::StringValue]
          #     Prefix before price. E.g. 'as low as'.
          # @!attribute [rw] promo_text
          #   @return [Google::Protobuf::StringValue]
          #     Promotion text used for dyanmic formats of responsive ads. For example
          #     'Free two-day shipping'.
          class LegacyResponsiveDisplayAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # An app ad.
          # @!attribute [rw] mandatory_ad_text
          #   @return [Google::Ads::GoogleAds::V3::Common::AdTextAsset]
          #     An optional text asset that, if specified, must always be displayed when
          #     the ad is served.
          # @!attribute [rw] headlines
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdTextAsset>]
          #     List of text assets for headlines. When the ad serves the headlines will
          #     be selected from this list.
          # @!attribute [rw] descriptions
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdTextAsset>]
          #     List of text assets for descriptions. When the ad serves the descriptions
          #     will be selected from this list.
          # @!attribute [rw] images
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdImageAsset>]
          #     List of image assets that may be displayed with the ad.
          # @!attribute [rw] youtube_videos
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdVideoAsset>]
          #     List of YouTube video assets that may be displayed with the ad.
          # @!attribute [rw] html5_media_bundles
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdMediaBundleAsset>]
          #     List of media bundle assets that may be used with the ad.
          class AppAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # App engagement ads allow you to write text encouraging a specific action in
          # the app, like checking in, making a purchase, or booking a flight.
          # They allow you to send users to a specific part of your app where they can
          # find what they're looking for easier and faster.
          # @!attribute [rw] headlines
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdTextAsset>]
          #     List of text assets for headlines. When the ad serves the headlines will
          #     be selected from this list.
          # @!attribute [rw] descriptions
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdTextAsset>]
          #     List of text assets for descriptions. When the ad serves the descriptions
          #     will be selected from this list.
          # @!attribute [rw] images
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdImageAsset>]
          #     List of image assets that may be displayed with the ad.
          # @!attribute [rw] videos
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdVideoAsset>]
          #     List of video assets that may be displayed with the ad.
          class AppEngagementAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A legacy app install ad that only can be used by a few select customers.
          # @!attribute [rw] app_id
          #   @return [Google::Protobuf::StringValue]
          #     The id of the mobile app.
          # @!attribute [rw] app_store
          #   @return [Google::Ads::GoogleAds::V3::Enums::LegacyAppInstallAdAppStoreEnum::LegacyAppInstallAdAppStore]
          #     The app store the mobile app is available in.
          # @!attribute [rw] headline
          #   @return [Google::Protobuf::StringValue]
          #     The headline of the ad.
          # @!attribute [rw] description1
          #   @return [Google::Protobuf::StringValue]
          #     The first description line of the ad.
          # @!attribute [rw] description2
          #   @return [Google::Protobuf::StringValue]
          #     The second description line of the ad.
          class LegacyAppInstallAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A responsive display ad.
          # @!attribute [rw] marketing_images
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdImageAsset>]
          #     Marketing images to be used in the ad. Valid image types are GIF,
          #     JPEG, and PNG. The minimum size is 600x314 and the aspect ratio must
          #     be 1.91:1 (+-1%). At least one marketing_image is required. Combined with
          #     square_marketing_images the maximum is 15.
          # @!attribute [rw] square_marketing_images
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdImageAsset>]
          #     Square marketing images to be used in the ad. Valid image types are GIF,
          #     JPEG, and PNG. The minimum size is 300x300 and the aspect ratio must
          #     be 1:1 (+-1%). At least one square marketing_image is required. Combined
          #     with marketing_images the maximum is 15.
          # @!attribute [rw] logo_images
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdImageAsset>]
          #     Logo images to be used in the ad. Valid image types are GIF,
          #     JPEG, and PNG. The minimum size is 512x128 and the aspect ratio must
          #     be 4:1 (+-1%). Combined with square_logo_images the maximum is 5.
          # @!attribute [rw] square_logo_images
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdImageAsset>]
          #     Square logo images to be used in the ad. Valid image types are GIF,
          #     JPEG, and PNG. The minimum size is 128x128 and the aspect ratio must
          #     be 1:1 (+-1%). Combined with square_logo_images the maximum is 5.
          # @!attribute [rw] headlines
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdTextAsset>]
          #     Short format headlines for the ad. The maximum length is 30 characters.
          #     At least 1 and max 5 headlines can be specified.
          # @!attribute [rw] long_headline
          #   @return [Google::Ads::GoogleAds::V3::Common::AdTextAsset]
          #     A required long format headline. The maximum length is 90 characters.
          # @!attribute [rw] descriptions
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdTextAsset>]
          #     Descriptive texts for the ad. The maximum length is 90 characters. At
          #     least 1 and max 5 headlines can be specified.
          # @!attribute [rw] youtube_videos
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::AdVideoAsset>]
          #     Optional YouTube videos for the ad. A maximum of 5 videos can be specified.
          # @!attribute [rw] business_name
          #   @return [Google::Protobuf::StringValue]
          #     The advertiser/brand name. Maximum display width is 25.
          # @!attribute [rw] main_color
          #   @return [Google::Protobuf::StringValue]
          #     The main color of the ad in hexadecimal, e.g. #ffffff for white.
          #     If one of main_color and accent_color is set, the other is required as
          #     well.
          # @!attribute [rw] accent_color
          #   @return [Google::Protobuf::StringValue]
          #     The accent color of the ad in hexadecimal, e.g. #ffffff for white.
          #     If one of main_color and accent_color is set, the other is required as
          #     well.
          # @!attribute [rw] allow_flexible_color
          #   @return [Google::Protobuf::BoolValue]
          #     Advertiser's consent to allow flexible color. When true, the ad may be
          #     served with different color if necessary. When false, the ad will be served
          #     with the specified colors or a neutral color.
          #     The default value is true.
          #     Must be true if main_color and accent_color are not set.
          # @!attribute [rw] call_to_action_text
          #   @return [Google::Protobuf::StringValue]
          #     The call-to-action text for the ad. Maximum display width is 30.
          # @!attribute [rw] price_prefix
          #   @return [Google::Protobuf::StringValue]
          #     Prefix before price. E.g. 'as low as'.
          # @!attribute [rw] promo_text
          #   @return [Google::Protobuf::StringValue]
          #     Promotion text used for dyanmic formats of responsive ads. For example
          #     'Free two-day shipping'.
          # @!attribute [rw] format_setting
          #   @return [Google::Ads::GoogleAds::V3::Enums::DisplayAdFormatSettingEnum::DisplayAdFormatSetting]
          #     Specifies which format the ad will be served in. Default is ALL_FORMATS.
          class ResponsiveDisplayAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A generic type of display ad. The exact ad format is controlled by the
          # display_upload_product_type field, which determines what kinds of data
          # need to be included with the ad.
          # @!attribute [rw] display_upload_product_type
          #   @return [Google::Ads::GoogleAds::V3::Enums::DisplayUploadProductTypeEnum::DisplayUploadProductType]
          #     The product type of this ad. See comments on the enum for details.
          # @!attribute [rw] media_bundle
          #   @return [Google::Ads::GoogleAds::V3::Common::AdMediaBundleAsset]
          #     A media bundle asset to be used in the ad. For information about the
          #     media bundle for HTML5_UPLOAD_AD see
          #     https://support.google.com/google-ads/answer/1722096
          #     Media bundles that are part of dynamic product types use a special format
          #     that needs to be created through the Google Web Designer. See
          #     https://support.google.com/webdesigner/answer/7543898 for more
          #     information.
          class DisplayUploadAdInfo
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
