# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Common
          # Settings for the targeting-related features, at the campaign and ad group
          # levels. For more details about the targeting setting, visit
          # https://support.google.com/google-ads/answer/7365594
          # @!attribute [rw] target_restrictions
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::TargetRestriction>]
          #     The per-targeting-dimension setting to restrict the reach of your campaign
          #     or ad group.
          # @!attribute [rw] target_restriction_operations
          #   @return [Array<Google::Ads::GoogleAds::V3::Common::TargetRestrictionOperation>]
          #     The list of operations changing the target restrictions.
          #
          #     Adding a target restriction with a targeting dimension that already exists
          #     causes the existing target restriction to be replaced with the new value.
          class TargetingSetting
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # The list of per-targeting-dimension targeting settings.
          # @!attribute [rw] targeting_dimension
          #   @return [Google::Ads::GoogleAds::V3::Enums::TargetingDimensionEnum::TargetingDimension]
          #     The targeting dimension that these settings apply to.
          # @!attribute [rw] bid_only
          #   @return [Google::Protobuf::BoolValue]
          #     Indicates whether to restrict your ads to show only for the criteria you
          #     have selected for this targeting_dimension, or to target all values for
          #     this targeting_dimension and show ads based on your targeting in other
          #     TargetingDimensions. A value of `true` means that these criteria will only
          #     apply bid modifiers, and not affect targeting. A value of `false` means
          #     that these criteria will restrict targeting as well as applying bid
          #     modifiers.
          class TargetRestriction
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Operation to be performed on a target restriction list in a mutate.
          # @!attribute [rw] operator
          #   @return [Google::Ads::GoogleAds::V3::Common::TargetRestrictionOperation::Operator]
          #     Type of list operation to perform.
          # @!attribute [rw] value
          #   @return [Google::Ads::GoogleAds::V3::Common::TargetRestriction]
          #     The target restriction being added to or removed from the list.
          class TargetRestrictionOperation
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # The operator.
            module Operator
              # Unspecified.
              UNSPECIFIED = 0

              # Used for return value only. Represents value unknown in this version.
              UNKNOWN = 1

              # Add the restriction to the existing restrictions.
              ADD = 2

              # Remove the restriction from the existing restrictions.
              REMOVE = 3
            end
          end
        end
      end
    end
  end
end
