:gem:
  :name: "google-ads-adsfull"
:defaults:
  :service:
    :default_host: "googleads.googleapis.com"
    :oauth_scopes:
      - https://www.googleapis.com/auth/adwords
:overrides:
  :namespace:
    Googleads: GoogleAds
