# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Services
          # Request message for
          # [ConversionAdjustmentUploadService.UploadConversionAdjustments][google.ads.googleads.v3.services.ConversionAdjustmentUploadService.UploadConversionAdjustments].
          # @!attribute [rw] customer_id
          #   @return [String]
          #     Required. The ID of the customer performing the upload.
          # @!attribute [rw] conversion_adjustments
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::ConversionAdjustment>]
          #     Required. The conversion adjustments that are being uploaded.
          # @!attribute [rw] partial_failure
          #   @return [Boolean]
          #     If true, successful operations will be carried out and invalid
          #     operations will return errors. If false, all operations will be carried out
          #     in one transaction if and only if they are all valid. This should always be
          #     set to true.
          # @!attribute [rw] validate_only
          #   @return [Boolean]
          #     If true, the request is validated but not executed. Only errors are
          #     returned, not results.
          class UploadConversionAdjustmentsRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Response message for
          # [ConversionAdjustmentUploadService.UploadConversionAdjustments][google.ads.googleads.v3.services.ConversionAdjustmentUploadService.UploadConversionAdjustments].
          # @!attribute [rw] partial_failure_error
          #   @return [Google::Rpc::Status]
          #     Errors that pertain to conversion adjustment failures in the partial
          #     failure mode. Returned when all errors occur inside the adjustments. If any
          #     errors occur outside the adjustments (e.g. auth errors), we return an RPC
          #     level error.
          # @!attribute [rw] results
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::ConversionAdjustmentResult>]
          #     Returned for successfully processed conversion adjustments. Proto will be
          #     empty for rows that received an error. Results are not returned when
          #     validate_only is true.
          class UploadConversionAdjustmentsResponse
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A conversion adjustment.
          # @!attribute [rw] conversion_action
          #   @return [Google::Protobuf::StringValue]
          #     Resource name of the conversion action associated with this conversion
          #     adjustment. Note: Although this resource name consists of a customer id and
          #     a conversion action id, validation will ignore the customer id and use the
          #     conversion action id as the sole identifier of the conversion action.
          # @!attribute [rw] adjustment_date_time
          #   @return [Google::Protobuf::StringValue]
          #     The date time at which the adjustment occurred. Must be after the
          #     conversion_date_time. The timezone must be specified. The format is
          #     "yyyy-mm-dd hh:mm:ss+|-hh:mm", e.g. "2019-01-01 12:32:45-08:00".
          # @!attribute [rw] adjustment_type
          #   @return [Google::Ads::GoogleAds::V3::Enums::ConversionAdjustmentTypeEnum::ConversionAdjustmentType]
          #     The adjustment type.
          # @!attribute [rw] restatement_value
          #   @return [Google::Ads::GoogleAds::V3::Services::RestatementValue]
          #     Information needed to restate the conversion's value.
          #     Required for restatements. Should not be supplied for retractions. An error
          #     will be returned if provided for a retraction.
          # @!attribute [rw] gclid_date_time_pair
          #   @return [Google::Ads::GoogleAds::V3::Services::GclidDateTimePair]
          #     Uniquely identifies a conversion that was reported without an order ID
          #     specified.
          # @!attribute [rw] order_id
          #   @return [Google::Protobuf::StringValue]
          #     The order ID of the conversion to be adjusted. If the conversion was
          #     reported with an order ID specified, that order ID must be used as the
          #     identifier here.
          class ConversionAdjustment
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Contains information needed to restate a conversion's value.
          # @!attribute [rw] adjusted_value
          #   @return [Google::Protobuf::DoubleValue]
          #     The restated conversion value. This is the value of the conversion after
          #     restatement. For example, to change the value of a conversion from 100 to
          #     70, an adjusted value of 70 should be reported.
          # @!attribute [rw] currency_code
          #   @return [Google::Protobuf::StringValue]
          #     The currency of the restated value. If not provided, then the default
          #     currency from the conversion action is used, and if that is not set then
          #     the account currency is used. This is the ISO 4217 3-character currency
          #     code e.g. USD or EUR.
          class RestatementValue
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Uniquely identifies a conversion that was reported without an order ID
          # specified.
          # @!attribute [rw] gclid
          #   @return [Google::Protobuf::StringValue]
          #     Google click ID (gclid) associated with the original conversion for this
          #     adjustment.
          # @!attribute [rw] conversion_date_time
          #   @return [Google::Protobuf::StringValue]
          #     The date time at which the original conversion for this adjustment
          #     occurred. The timezone must be specified. The format is "yyyy-mm-dd
          #     hh:mm:ss+|-hh:mm", e.g. "2019-01-01 12:32:45-08:00".
          class GclidDateTimePair
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Information identifying a successfully processed ConversionAdjustment.
          # @!attribute [rw] conversion_action
          #   @return [Google::Protobuf::StringValue]
          #     Resource name of the conversion action associated with this conversion
          #     adjustment.
          # @!attribute [rw] adjustment_date_time
          #   @return [Google::Protobuf::StringValue]
          #     The date time at which the adjustment occurred. The format is
          #     "yyyy-mm-dd hh:mm:ss+|-hh:mm", e.g. "2019-01-01 12:32:45-08:00".
          # @!attribute [rw] adjustment_type
          #   @return [Google::Ads::GoogleAds::V3::Enums::ConversionAdjustmentTypeEnum::ConversionAdjustmentType]
          #     The adjustment type.
          # @!attribute [rw] gclid_date_time_pair
          #   @return [Google::Ads::GoogleAds::V3::Services::GclidDateTimePair]
          #     Uniquely identifies a conversion that was reported without an order ID
          #     specified.
          # @!attribute [rw] order_id
          #   @return [Google::Protobuf::StringValue]
          #     The order ID of the conversion that was adjusted.
          class ConversionAdjustmentResult
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
