# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Services
          # Request message for [GeoTargetConstantService.GetGeoTargetConstant][google.ads.googleads.v3.services.GeoTargetConstantService.GetGeoTargetConstant].
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Required. The resource name of the geo target constant to fetch.
          class GetGeoTargetConstantRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Request message for
          # [GeoTargetConstantService.SuggestGeoTargetConstantsRequest][].
          # @!attribute [rw] locale
          #   @return [Google::Protobuf::StringValue]
          #     If possible, returned geo targets are translated using this locale. If not,
          #     en is used by default. This is also used as a hint for returned geo
          #     targets.
          # @!attribute [rw] country_code
          #   @return [Google::Protobuf::StringValue]
          #     Returned geo targets are restricted to this country code.
          # @!attribute [rw] location_names
          #   @return [Google::Ads::GoogleAds::V3::Services::SuggestGeoTargetConstantsRequest::LocationNames]
          #     The location names to search by. At most 25 names can be set.
          # @!attribute [rw] geo_targets
          #   @return [Google::Ads::GoogleAds::V3::Services::SuggestGeoTargetConstantsRequest::GeoTargets]
          #     The geo target constant resource names to filter by.
          class SuggestGeoTargetConstantsRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # A list of location names.
            # @!attribute [rw] names
            #   @return [Array<Google::Protobuf::StringValue>]
            #     A list of location names.
            class LocationNames
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end

            # A list of geo target constant resource names.
            # @!attribute [rw] geo_target_constants
            #   @return [Array<Google::Protobuf::StringValue>]
            #     A list of geo target constant resource names.
            class GeoTargets
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end
          end

          # Response message for [GeoTargetConstantService.SuggestGeoTargetConstants][google.ads.googleads.v3.services.GeoTargetConstantService.SuggestGeoTargetConstants]
          # @!attribute [rw] geo_target_constant_suggestions
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::GeoTargetConstantSuggestion>]
          #     Geo target constant suggestions.
          class SuggestGeoTargetConstantsResponse
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A geo target constant suggestion.
          # @!attribute [rw] locale
          #   @return [Google::Protobuf::StringValue]
          #     The language this GeoTargetConstantSuggestion is currently translated to.
          #     It affects the name of geo target fields. For example, if locale=en, then
          #     name=Spain. If locale=es, then name=España. The default locale will be
          #     returned if no translation exists for the locale in the request.
          # @!attribute [rw] reach
          #   @return [Google::Protobuf::Int64Value]
          #     Approximate user population that will be targeted, rounded to the
          #     nearest 100.
          # @!attribute [rw] search_term
          #   @return [Google::Protobuf::StringValue]
          #     If the request searched by location name, this is the location name that
          #     matched the geo target.
          # @!attribute [rw] geo_target_constant
          #   @return [Google::Ads::GoogleAds::V3::Resources::GeoTargetConstant]
          #     The GeoTargetConstant result.
          # @!attribute [rw] geo_target_constant_parents
          #   @return [Array<Google::Ads::GoogleAds::V3::Resources::GeoTargetConstant>]
          #     The list of parents of the geo target constant.
          class GeoTargetConstantSuggestion
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
