# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Services
          # Request message for [GoogleAdsService.Search][google.ads.googleads.v3.services.GoogleAdsService.Search].
          # @!attribute [rw] customer_id
          #   @return [String]
          #     Required. The ID of the customer being queried.
          # @!attribute [rw] query
          #   @return [String]
          #     Required. The query string.
          # @!attribute [rw] page_token
          #   @return [String]
          #     Token of the page to retrieve. If not specified, the first
          #     page of results will be returned. Use the value obtained from
          #     `next_page_token` in the previous response in order to request
          #     the next page of results.
          # @!attribute [rw] page_size
          #   @return [Integer]
          #     Number of elements to retrieve in a single page.
          #     When too large a page is requested, the server may decide to
          #     further limit the number of returned resources.
          # @!attribute [rw] validate_only
          #   @return [Boolean]
          #     If true, the request is validated but not executed.
          # @!attribute [rw] return_total_results_count
          #   @return [Boolean]
          #     If true, the total number of results that match the query ignoring the
          #     LIMIT clause will be included in the response.
          #     Default is false.
          # @!attribute [rw] summary_row_setting
          #   @return [Google::Ads::GoogleAds::V3::Enums::SummaryRowSettingEnum::SummaryRowSetting]
          #     Determines whether a summary row will be returned. By default, summary row
          #     is not returned. If requested, the summary row will be sent in a response
          #     by itself after all other query results are returned.
          class SearchGoogleAdsRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Response message for [GoogleAdsService.Search][google.ads.googleads.v3.services.GoogleAdsService.Search].
          # @!attribute [rw] results
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::GoogleAdsRow>]
          #     The list of rows that matched the query.
          # @!attribute [rw] next_page_token
          #   @return [String]
          #     Pagination token used to retrieve the next page of results.
          #     Pass the content of this string as the `page_token` attribute of
          #     the next request. `next_page_token` is not returned for the last
          #     page.
          # @!attribute [rw] total_results_count
          #   @return [Integer]
          #     Total number of results that match the query ignoring the LIMIT
          #     clause.
          # @!attribute [rw] field_mask
          #   @return [Google::Protobuf::FieldMask]
          #     FieldMask that represents what fields were requested by the user.
          # @!attribute [rw] summary_row
          #   @return [Google::Ads::GoogleAds::V3::Services::GoogleAdsRow]
          #     Summary row that contains summary of metrics in results.
          #     Summary of metrics means aggregation of metrics across all results,
          #     here aggregation could be sum, average, rate, etc.
          class SearchGoogleAdsResponse
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Request message for [GoogleAdsService.SearchStream][google.ads.googleads.v3.services.GoogleAdsService.SearchStream].
          # Next tag: 5
          # @!attribute [rw] customer_id
          #   @return [String]
          #     Required. The ID of the customer being queried.
          # @!attribute [rw] query
          #   @return [String]
          #     Required. The query string.
          # @!attribute [rw] summary_row_setting
          #   @return [Google::Ads::GoogleAds::V3::Enums::SummaryRowSettingEnum::SummaryRowSetting]
          #     Determines whether a summary row will be returned. By default, summary row
          #     is not returned. If requested, the summary row will be sent in a response
          #     by itself after all other query results are returned.
          class SearchGoogleAdsStreamRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Response message for [GoogleAdsService.SearchStream][google.ads.googleads.v3.services.GoogleAdsService.SearchStream].
          # @!attribute [rw] results
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::GoogleAdsRow>]
          #     The list of rows that matched the query.
          # @!attribute [rw] field_mask
          #   @return [Google::Protobuf::FieldMask]
          #     FieldMask that represents what fields were requested by the user.
          # @!attribute [rw] summary_row
          #   @return [Google::Ads::GoogleAds::V3::Services::GoogleAdsRow]
          #     Summary row that contains summary of metrics in results.
          #     Summary of metrics means aggregation of metrics across all results,
          #     here aggregation could be sum, average, rate, etc.
          class SearchGoogleAdsStreamResponse
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A returned row from the query.
          # @!attribute [rw] account_budget
          #   @return [Google::Ads::GoogleAds::V3::Resources::AccountBudget]
          #     The account budget in the query.
          # @!attribute [rw] account_budget_proposal
          #   @return [Google::Ads::GoogleAds::V3::Resources::AccountBudgetProposal]
          #     The account budget proposal referenced in the query.
          # @!attribute [rw] ad_group
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroup]
          #     The ad group referenced in the query.
          # @!attribute [rw] ad_group_ad
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroupAd]
          #     The ad referenced in the query.
          # @!attribute [rw] ad_group_ad_asset_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroupAdAssetView]
          #     The ad group ad asset view in the query.
          # @!attribute [rw] ad_group_ad_label
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroupAdLabel]
          #     The ad group ad label referenced in the query.
          # @!attribute [rw] ad_group_audience_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroupAudienceView]
          #     The ad group audience view referenced in the query.
          # @!attribute [rw] ad_group_bid_modifier
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroupBidModifier]
          #     The bid modifier referenced in the query.
          # @!attribute [rw] ad_group_criterion
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroupCriterion]
          #     The criterion referenced in the query.
          # @!attribute [rw] ad_group_criterion_label
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroupCriterionLabel]
          #     The ad group criterion label referenced in the query.
          # @!attribute [rw] ad_group_criterion_simulation
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroupCriterionSimulation]
          #     The ad group criterion simulation referenced in the query.
          # @!attribute [rw] ad_group_extension_setting
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroupExtensionSetting]
          #     The ad group extension setting referenced in the query.
          # @!attribute [rw] ad_group_feed
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroupFeed]
          #     The ad group feed referenced in the query.
          # @!attribute [rw] ad_group_label
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroupLabel]
          #     The ad group label referenced in the query.
          # @!attribute [rw] ad_group_simulation
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdGroupSimulation]
          #     The ad group simulation referenced in the query.
          # @!attribute [rw] ad_parameter
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdParameter]
          #     The ad parameter referenced in the query.
          # @!attribute [rw] age_range_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::AgeRangeView]
          #     The age range view referenced in the query.
          # @!attribute [rw] ad_schedule_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::AdScheduleView]
          #     The ad schedule view referenced in the query.
          # @!attribute [rw] domain_category
          #   @return [Google::Ads::GoogleAds::V3::Resources::DomainCategory]
          #     The domain category referenced in the query.
          # @!attribute [rw] asset
          #   @return [Google::Ads::GoogleAds::V3::Resources::Asset]
          #     The asset referenced in the query.
          # @!attribute [rw] bidding_strategy
          #   @return [Google::Ads::GoogleAds::V3::Resources::BiddingStrategy]
          #     The bidding strategy referenced in the query.
          # @!attribute [rw] billing_setup
          #   @return [Google::Ads::GoogleAds::V3::Resources::BillingSetup]
          #     The billing setup referenced in the query.
          # @!attribute [rw] campaign_budget
          #   @return [Google::Ads::GoogleAds::V3::Resources::CampaignBudget]
          #     The campaign budget referenced in the query.
          # @!attribute [rw] campaign
          #   @return [Google::Ads::GoogleAds::V3::Resources::Campaign]
          #     The campaign referenced in the query.
          # @!attribute [rw] campaign_audience_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::CampaignAudienceView]
          #     The campaign audience view referenced in the query.
          # @!attribute [rw] campaign_bid_modifier
          #   @return [Google::Ads::GoogleAds::V3::Resources::CampaignBidModifier]
          #     The campaign bid modifier referenced in the query.
          # @!attribute [rw] campaign_criterion
          #   @return [Google::Ads::GoogleAds::V3::Resources::CampaignCriterion]
          #     The campaign criterion referenced in the query.
          # @!attribute [rw] campaign_criterion_simulation
          #   @return [Google::Ads::GoogleAds::V3::Resources::CampaignCriterionSimulation]
          #     The campaign criterion simulation referenced in the query.
          # @!attribute [rw] campaign_draft
          #   @return [Google::Ads::GoogleAds::V3::Resources::CampaignDraft]
          #     The campaign draft referenced in the query.
          # @!attribute [rw] campaign_experiment
          #   @return [Google::Ads::GoogleAds::V3::Resources::CampaignExperiment]
          #     The campaign experiment referenced in the query.
          # @!attribute [rw] campaign_extension_setting
          #   @return [Google::Ads::GoogleAds::V3::Resources::CampaignExtensionSetting]
          #     The campaign extension setting referenced in the query.
          # @!attribute [rw] campaign_feed
          #   @return [Google::Ads::GoogleAds::V3::Resources::CampaignFeed]
          #     The campaign feed referenced in the query.
          # @!attribute [rw] campaign_label
          #   @return [Google::Ads::GoogleAds::V3::Resources::CampaignLabel]
          #     The campaign label referenced in the query.
          # @!attribute [rw] campaign_shared_set
          #   @return [Google::Ads::GoogleAds::V3::Resources::CampaignSharedSet]
          #     Campaign Shared Set referenced in AWQL query.
          # @!attribute [rw] carrier_constant
          #   @return [Google::Ads::GoogleAds::V3::Resources::CarrierConstant]
          #     The carrier constant referenced in the query.
          # @!attribute [rw] change_status
          #   @return [Google::Ads::GoogleAds::V3::Resources::ChangeStatus]
          #     The ChangeStatus referenced in the query.
          # @!attribute [rw] conversion_action
          #   @return [Google::Ads::GoogleAds::V3::Resources::ConversionAction]
          #     The conversion action referenced in the query.
          # @!attribute [rw] click_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::ClickView]
          #     The ClickView referenced in the query.
          # @!attribute [rw] currency_constant
          #   @return [Google::Ads::GoogleAds::V3::Resources::CurrencyConstant]
          #     The currency constant referenced in the query.
          # @!attribute [rw] custom_interest
          #   @return [Google::Ads::GoogleAds::V3::Resources::CustomInterest]
          #     The CustomInterest referenced in the query.
          # @!attribute [rw] customer
          #   @return [Google::Ads::GoogleAds::V3::Resources::Customer]
          #     The customer referenced in the query.
          # @!attribute [rw] customer_manager_link
          #   @return [Google::Ads::GoogleAds::V3::Resources::CustomerManagerLink]
          #     The CustomerManagerLink referenced in the query.
          # @!attribute [rw] customer_client_link
          #   @return [Google::Ads::GoogleAds::V3::Resources::CustomerClientLink]
          #     The CustomerClientLink referenced in the query.
          # @!attribute [rw] customer_client
          #   @return [Google::Ads::GoogleAds::V3::Resources::CustomerClient]
          #     The CustomerClient referenced in the query.
          # @!attribute [rw] customer_extension_setting
          #   @return [Google::Ads::GoogleAds::V3::Resources::CustomerExtensionSetting]
          #     The customer extension setting referenced in the query.
          # @!attribute [rw] customer_feed
          #   @return [Google::Ads::GoogleAds::V3::Resources::CustomerFeed]
          #     The customer feed referenced in the query.
          # @!attribute [rw] customer_label
          #   @return [Google::Ads::GoogleAds::V3::Resources::CustomerLabel]
          #     The customer label referenced in the query.
          # @!attribute [rw] customer_negative_criterion
          #   @return [Google::Ads::GoogleAds::V3::Resources::CustomerNegativeCriterion]
          #     The customer negative criterion referenced in the query.
          # @!attribute [rw] detail_placement_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::DetailPlacementView]
          #     The detail placement view referenced in the query.
          # @!attribute [rw] display_keyword_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::DisplayKeywordView]
          #     The display keyword view referenced in the query.
          # @!attribute [rw] distance_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::DistanceView]
          #     The distance view referenced in the query.
          # @!attribute [rw] dynamic_search_ads_search_term_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::DynamicSearchAdsSearchTermView]
          #     The dynamic search ads search term view referenced in the query.
          # @!attribute [rw] expanded_landing_page_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::ExpandedLandingPageView]
          #     The expanded landing page view referenced in the query.
          # @!attribute [rw] extension_feed_item
          #   @return [Google::Ads::GoogleAds::V3::Resources::ExtensionFeedItem]
          #     The extension feed item referenced in the query.
          # @!attribute [rw] feed
          #   @return [Google::Ads::GoogleAds::V3::Resources::Feed]
          #     The feed referenced in the query.
          # @!attribute [rw] feed_item
          #   @return [Google::Ads::GoogleAds::V3::Resources::FeedItem]
          #     The feed item referenced in the query.
          # @!attribute [rw] feed_item_target
          #   @return [Google::Ads::GoogleAds::V3::Resources::FeedItemTarget]
          #     The feed item target referenced in the query.
          # @!attribute [rw] feed_mapping
          #   @return [Google::Ads::GoogleAds::V3::Resources::FeedMapping]
          #     The feed mapping referenced in the query.
          # @!attribute [rw] feed_placeholder_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::FeedPlaceholderView]
          #     The feed placeholder view referenced in the query.
          # @!attribute [rw] gender_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::GenderView]
          #     The gender view referenced in the query.
          # @!attribute [rw] geo_target_constant
          #   @return [Google::Ads::GoogleAds::V3::Resources::GeoTargetConstant]
          #     The geo target constant referenced in the query.
          # @!attribute [rw] geographic_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::GeographicView]
          #     The geographic view referenced in the query.
          # @!attribute [rw] group_placement_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::GroupPlacementView]
          #     The group placement view referenced in the query.
          # @!attribute [rw] hotel_group_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::HotelGroupView]
          #     The hotel group view referenced in the query.
          # @!attribute [rw] hotel_performance_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::HotelPerformanceView]
          #     The hotel performance view referenced in the query.
          # @!attribute [rw] keyword_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::KeywordView]
          #     The keyword view referenced in the query.
          # @!attribute [rw] keyword_plan
          #   @return [Google::Ads::GoogleAds::V3::Resources::KeywordPlan]
          #     The keyword plan referenced in the query.
          # @!attribute [rw] keyword_plan_campaign
          #   @return [Google::Ads::GoogleAds::V3::Resources::KeywordPlanCampaign]
          #     The keyword plan campaign referenced in the query.
          # @!attribute [rw] keyword_plan_negative_keyword
          #   @return [Google::Ads::GoogleAds::V3::Resources::KeywordPlanNegativeKeyword]
          #     The keyword plan negative keyword referenced in the query.
          # @!attribute [rw] keyword_plan_ad_group
          #   @return [Google::Ads::GoogleAds::V3::Resources::KeywordPlanAdGroup]
          #     The keyword plan ad group referenced in the query.
          # @!attribute [rw] keyword_plan_keyword
          #   @return [Google::Ads::GoogleAds::V3::Resources::KeywordPlanKeyword]
          #     The keyword plan keyword referenced in the query.
          # @!attribute [rw] label
          #   @return [Google::Ads::GoogleAds::V3::Resources::Label]
          #     The label referenced in the query.
          # @!attribute [rw] landing_page_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::LandingPageView]
          #     The landing page view referenced in the query.
          # @!attribute [rw] language_constant
          #   @return [Google::Ads::GoogleAds::V3::Resources::LanguageConstant]
          #     The language constant referenced in the query.
          # @!attribute [rw] location_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::LocationView]
          #     The location view referenced in the query.
          # @!attribute [rw] managed_placement_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::ManagedPlacementView]
          #     The managed placement view referenced in the query.
          # @!attribute [rw] media_file
          #   @return [Google::Ads::GoogleAds::V3::Resources::MediaFile]
          #     The media file referenced in the query.
          # @!attribute [rw] mobile_app_category_constant
          #   @return [Google::Ads::GoogleAds::V3::Resources::MobileAppCategoryConstant]
          #     The mobile app category constant referenced in the query.
          # @!attribute [rw] mobile_device_constant
          #   @return [Google::Ads::GoogleAds::V3::Resources::MobileDeviceConstant]
          #     The mobile device constant referenced in the query.
          # @!attribute [rw] mutate_job
          #   @return [Google::Ads::GoogleAds::V3::Resources::MutateJob]
          #     The mutate job referenced in the query.
          # @!attribute [rw] operating_system_version_constant
          #   @return [Google::Ads::GoogleAds::V3::Resources::OperatingSystemVersionConstant]
          #     The operating system version constant referenced in the query.
          # @!attribute [rw] paid_organic_search_term_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::PaidOrganicSearchTermView]
          #     The paid organic search term view referenced in the query.
          # @!attribute [rw] parental_status_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::ParentalStatusView]
          #     The parental status view referenced in the query.
          # @!attribute [rw] product_bidding_category_constant
          #   @return [Google::Ads::GoogleAds::V3::Resources::ProductBiddingCategoryConstant]
          #     The Product Bidding Category referenced in the query.
          # @!attribute [rw] product_group_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::ProductGroupView]
          #     The product group view referenced in the query.
          # @!attribute [rw] recommendation
          #   @return [Google::Ads::GoogleAds::V3::Resources::Recommendation]
          #     The recommendation referenced in the query.
          # @!attribute [rw] search_term_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::SearchTermView]
          #     The search term view referenced in the query.
          # @!attribute [rw] shared_criterion
          #   @return [Google::Ads::GoogleAds::V3::Resources::SharedCriterion]
          #     The shared set referenced in the query.
          # @!attribute [rw] shared_set
          #   @return [Google::Ads::GoogleAds::V3::Resources::SharedSet]
          #     The shared set referenced in the query.
          # @!attribute [rw] shopping_performance_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::ShoppingPerformanceView]
          #     The shopping performance view referenced in the query.
          # @!attribute [rw] topic_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::TopicView]
          #     The topic view referenced in the query.
          # @!attribute [rw] user_interest
          #   @return [Google::Ads::GoogleAds::V3::Resources::UserInterest]
          #     The user interest referenced in the query.
          # @!attribute [rw] user_list
          #   @return [Google::Ads::GoogleAds::V3::Resources::UserList]
          #     The user list referenced in the query.
          # @!attribute [rw] user_location_view
          #   @return [Google::Ads::GoogleAds::V3::Resources::UserLocationView]
          #     The user location view referenced in the query.
          # @!attribute [rw] remarketing_action
          #   @return [Google::Ads::GoogleAds::V3::Resources::RemarketingAction]
          #     The remarketing action referenced in the query.
          # @!attribute [rw] topic_constant
          #   @return [Google::Ads::GoogleAds::V3::Resources::TopicConstant]
          #     The topic constant referenced in the query.
          # @!attribute [rw] video
          #   @return [Google::Ads::GoogleAds::V3::Resources::Video]
          #     The video referenced in the query.
          # @!attribute [rw] metrics
          #   @return [Google::Ads::GoogleAds::V3::Common::Metrics]
          #     The metrics.
          # @!attribute [rw] segments
          #   @return [Google::Ads::GoogleAds::V3::Common::Segments]
          #     The segments.
          class GoogleAdsRow
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Request message for [GoogleAdsService.Mutate][google.ads.googleads.v3.services.GoogleAdsService.Mutate].
          # @!attribute [rw] customer_id
          #   @return [String]
          #     Required. The ID of the customer whose resources are being modified.
          # @!attribute [rw] mutate_operations
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::MutateOperation>]
          #     Required. The list of operations to perform on individual resources.
          # @!attribute [rw] partial_failure
          #   @return [Boolean]
          #     If true, successful operations will be carried out and invalid
          #     operations will return errors. If false, all operations will be carried
          #     out in one transaction if and only if they are all valid.
          #     Default is false.
          # @!attribute [rw] validate_only
          #   @return [Boolean]
          #     If true, the request is validated but not executed. Only errors are
          #     returned, not results.
          class MutateGoogleAdsRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Response message for [GoogleAdsService.Mutate][google.ads.googleads.v3.services.GoogleAdsService.Mutate].
          # @!attribute [rw] partial_failure_error
          #   @return [Google::Rpc::Status]
          #     Errors that pertain to operation failures in the partial failure mode.
          #     Returned only when partial_failure = true and all errors occur inside the
          #     operations. If any errors occur outside the operations (e.g., auth errors),
          #     we return an RPC level error.
          # @!attribute [rw] mutate_operation_responses
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::MutateOperationResponse>]
          #     All responses for the mutate.
          class MutateGoogleAdsResponse
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A single operation (create, update, remove) on a resource.
          # @!attribute [rw] ad_group_ad_label_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::AdGroupAdLabelOperation]
          #     An ad group ad label mutate operation.
          # @!attribute [rw] ad_group_ad_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::AdGroupAdOperation]
          #     An ad group ad mutate operation.
          # @!attribute [rw] ad_group_bid_modifier_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::AdGroupBidModifierOperation]
          #     An ad group bid modifier mutate operation.
          # @!attribute [rw] ad_group_criterion_label_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::AdGroupCriterionLabelOperation]
          #     An ad group criterion label mutate operation.
          # @!attribute [rw] ad_group_criterion_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::AdGroupCriterionOperation]
          #     An ad group criterion mutate operation.
          # @!attribute [rw] ad_group_extension_setting_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::AdGroupExtensionSettingOperation]
          #     An ad group extension setting mutate operation.
          # @!attribute [rw] ad_group_feed_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::AdGroupFeedOperation]
          #     An ad group feed mutate operation.
          # @!attribute [rw] ad_group_label_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::AdGroupLabelOperation]
          #     An ad group label mutate operation.
          # @!attribute [rw] ad_group_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::AdGroupOperation]
          #     An ad group mutate operation.
          # @!attribute [rw] ad_parameter_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::AdParameterOperation]
          #     An ad parameter mutate operation.
          # @!attribute [rw] asset_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::AssetOperation]
          #     An asset mutate operation.
          # @!attribute [rw] bidding_strategy_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::BiddingStrategyOperation]
          #     A bidding strategy mutate operation.
          # @!attribute [rw] campaign_bid_modifier_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CampaignBidModifierOperation]
          #     A campaign bid modifier mutate operation.
          # @!attribute [rw] campaign_budget_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CampaignBudgetOperation]
          #     A campaign budget mutate operation.
          # @!attribute [rw] campaign_criterion_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CampaignCriterionOperation]
          #     A campaign criterion mutate operation.
          # @!attribute [rw] campaign_draft_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CampaignDraftOperation]
          #     A campaign draft mutate operation.
          # @!attribute [rw] campaign_experiment_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CampaignExperimentOperation]
          #     A campaign experiment mutate operation.
          # @!attribute [rw] campaign_extension_setting_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CampaignExtensionSettingOperation]
          #     A campaign extension setting mutate operation.
          # @!attribute [rw] campaign_feed_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CampaignFeedOperation]
          #     A campaign feed mutate operation.
          # @!attribute [rw] campaign_label_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CampaignLabelOperation]
          #     A campaign label mutate operation.
          # @!attribute [rw] campaign_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CampaignOperation]
          #     A campaign mutate operation.
          # @!attribute [rw] campaign_shared_set_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CampaignSharedSetOperation]
          #     A campaign shared set mutate operation.
          # @!attribute [rw] conversion_action_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::ConversionActionOperation]
          #     A conversion action mutate operation.
          # @!attribute [rw] customer_extension_setting_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CustomerExtensionSettingOperation]
          #     A customer extension setting mutate operation.
          # @!attribute [rw] customer_feed_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CustomerFeedOperation]
          #     A customer feed mutate operation.
          # @!attribute [rw] customer_label_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CustomerLabelOperation]
          #     A customer label mutate operation.
          # @!attribute [rw] customer_negative_criterion_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CustomerNegativeCriterionOperation]
          #     A customer negative criterion mutate operation.
          # @!attribute [rw] customer_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::CustomerOperation]
          #     A customer mutate operation.
          # @!attribute [rw] extension_feed_item_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::ExtensionFeedItemOperation]
          #     An extension feed item mutate operation.
          # @!attribute [rw] feed_item_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::FeedItemOperation]
          #     A feed item mutate operation.
          # @!attribute [rw] feed_item_target_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::FeedItemTargetOperation]
          #     A feed item target mutate operation.
          # @!attribute [rw] feed_mapping_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::FeedMappingOperation]
          #     A feed mapping mutate operation.
          # @!attribute [rw] feed_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::FeedOperation]
          #     A feed mutate operation.
          # @!attribute [rw] label_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::LabelOperation]
          #     A label mutate operation.
          # @!attribute [rw] media_file_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::MediaFileOperation]
          #     A media file mutate operation.
          # @!attribute [rw] remarketing_action_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::RemarketingActionOperation]
          #     A remarketing action mutate operation.
          # @!attribute [rw] shared_criterion_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::SharedCriterionOperation]
          #     A shared criterion mutate operation.
          # @!attribute [rw] shared_set_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::SharedSetOperation]
          #     A shared set mutate operation.
          # @!attribute [rw] user_list_operation
          #   @return [Google::Ads::GoogleAds::V3::Services::UserListOperation]
          #     A user list mutate operation.
          class MutateOperation
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Response message for the resource mutate.
          # @!attribute [rw] ad_group_ad_label_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateAdGroupAdLabelResult]
          #     The result for the ad group ad label mutate.
          # @!attribute [rw] ad_group_ad_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateAdGroupAdResult]
          #     The result for the ad group ad mutate.
          # @!attribute [rw] ad_group_bid_modifier_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateAdGroupBidModifierResult]
          #     The result for the ad group bid modifier mutate.
          # @!attribute [rw] ad_group_criterion_label_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateAdGroupCriterionLabelResult]
          #     The result for the ad group criterion label mutate.
          # @!attribute [rw] ad_group_criterion_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateAdGroupCriterionResult]
          #     The result for the ad group criterion mutate.
          # @!attribute [rw] ad_group_extension_setting_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateAdGroupExtensionSettingResult]
          #     The result for the ad group extension setting mutate.
          # @!attribute [rw] ad_group_feed_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateAdGroupFeedResult]
          #     The result for the ad group feed mutate.
          # @!attribute [rw] ad_group_label_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateAdGroupLabelResult]
          #     The result for the ad group label mutate.
          # @!attribute [rw] ad_group_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateAdGroupResult]
          #     The result for the ad group mutate.
          # @!attribute [rw] ad_parameter_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateAdParameterResult]
          #     The result for the ad parameter mutate.
          # @!attribute [rw] asset_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateAssetResult]
          #     The result for the asset mutate.
          # @!attribute [rw] bidding_strategy_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateBiddingStrategyResult]
          #     The result for the bidding strategy mutate.
          # @!attribute [rw] campaign_bid_modifier_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCampaignBidModifierResult]
          #     The result for the campaign bid modifier mutate.
          # @!attribute [rw] campaign_budget_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCampaignBudgetResult]
          #     The result for the campaign budget mutate.
          # @!attribute [rw] campaign_criterion_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCampaignCriterionResult]
          #     The result for the campaign criterion mutate.
          # @!attribute [rw] campaign_draft_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCampaignDraftResult]
          #     The result for the campaign draft mutate.
          # @!attribute [rw] campaign_experiment_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCampaignExperimentResult]
          #     The result for the campaign experiment mutate.
          # @!attribute [rw] campaign_extension_setting_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCampaignExtensionSettingResult]
          #     The result for the campaign extension setting mutate.
          # @!attribute [rw] campaign_feed_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCampaignFeedResult]
          #     The result for the campaign feed mutate.
          # @!attribute [rw] campaign_label_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCampaignLabelResult]
          #     The result for the campaign label mutate.
          # @!attribute [rw] campaign_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCampaignResult]
          #     The result for the campaign mutate.
          # @!attribute [rw] campaign_shared_set_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCampaignSharedSetResult]
          #     The result for the campaign shared set mutate.
          # @!attribute [rw] conversion_action_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateConversionActionResult]
          #     The result for the conversion action mutate.
          # @!attribute [rw] customer_extension_setting_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCustomerExtensionSettingResult]
          #     The result for the customer extension setting mutate.
          # @!attribute [rw] customer_feed_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCustomerFeedResult]
          #     The result for the customer feed mutate.
          # @!attribute [rw] customer_label_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCustomerLabelResult]
          #     The result for the customer label mutate.
          # @!attribute [rw] customer_negative_criterion_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCustomerNegativeCriteriaResult]
          #     The result for the customer negative criterion mutate.
          # @!attribute [rw] customer_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateCustomerResult]
          #     The result for the customer mutate.
          # @!attribute [rw] extension_feed_item_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateExtensionFeedItemResult]
          #     The result for the extension feed item mutate.
          # @!attribute [rw] feed_item_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateFeedItemResult]
          #     The result for the feed item mutate.
          # @!attribute [rw] feed_item_target_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateFeedItemTargetResult]
          #     The result for the feed item target mutate.
          # @!attribute [rw] feed_mapping_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateFeedMappingResult]
          #     The result for the feed mapping mutate.
          # @!attribute [rw] feed_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateFeedResult]
          #     The result for the feed mutate.
          # @!attribute [rw] label_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateLabelResult]
          #     The result for the label mutate.
          # @!attribute [rw] media_file_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateMediaFileResult]
          #     The result for the media file mutate.
          # @!attribute [rw] remarketing_action_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateRemarketingActionResult]
          #     The result for the remarketing action mutate.
          # @!attribute [rw] shared_criterion_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateSharedCriterionResult]
          #     The result for the shared criterion mutate.
          # @!attribute [rw] shared_set_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateSharedSetResult]
          #     The result for the shared set mutate.
          # @!attribute [rw] user_list_result
          #   @return [Google::Ads::GoogleAds::V3::Services::MutateUserListResult]
          #     The result for the user list mutate.
          class MutateOperationResponse
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
