# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Services
          # Request message for [GoogleAdsFieldService.GetGoogleAdsField][google.ads.googleads.v3.services.GoogleAdsFieldService.GetGoogleAdsField].
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Required. The resource name of the field to get.
          class GetGoogleAdsFieldRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Request message for [GoogleAdsFieldService.SearchGoogleAdsFields][google.ads.googleads.v3.services.GoogleAdsFieldService.SearchGoogleAdsFields].
          # @!attribute [rw] query
          #   @return [String]
          #     Required. The query string.
          # @!attribute [rw] page_token
          #   @return [String]
          #     Token of the page to retrieve. If not specified, the first page of
          #     results will be returned. Use the value obtained from `next_page_token`
          #     in the previous response in order to request the next page of results.
          # @!attribute [rw] page_size
          #   @return [Integer]
          #     Number of elements to retrieve in a single page.
          #     When too large a page is requested, the server may decide to further
          #     limit the number of returned resources.
          class SearchGoogleAdsFieldsRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Response message for [GoogleAdsFieldService.SearchGoogleAdsFields][google.ads.googleads.v3.services.GoogleAdsFieldService.SearchGoogleAdsFields].
          # @!attribute [rw] results
          #   @return [Array<Google::Ads::GoogleAds::V3::Resources::GoogleAdsField>]
          #     The list of fields that matched the query.
          # @!attribute [rw] next_page_token
          #   @return [String]
          #     Pagination token used to retrieve the next page of results. Pass the
          #     content of this string as the `page_token` attribute of the next request.
          #     `next_page_token` is not returned for the last page.
          # @!attribute [rw] total_results_count
          #   @return [Integer]
          #     Total number of results that match the query ignoring the LIMIT clause.
          class SearchGoogleAdsFieldsResponse
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
