# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Services
          # Request message for [RecommendationService.GetRecommendation][google.ads.googleads.v3.services.RecommendationService.GetRecommendation].
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Required. The resource name of the recommendation to fetch.
          class GetRecommendationRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Request message for [RecommendationService.ApplyRecommendation][google.ads.googleads.v3.services.RecommendationService.ApplyRecommendation].
          # @!attribute [rw] customer_id
          #   @return [String]
          #     Required. The ID of the customer with the recommendation.
          # @!attribute [rw] operations
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::ApplyRecommendationOperation>]
          #     Required. The list of operations to apply recommendations.
          #     If partial_failure=false all recommendations should be of the same type
          #     There is a limit of 100 operations per request.
          # @!attribute [rw] partial_failure
          #   @return [Boolean]
          #     If true, successful operations will be carried out and invalid
          #     operations will return errors. If false, operations will be carried
          #     out as a transaction if and only if they are all valid.
          #     Default is false.
          class ApplyRecommendationRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Information about the operation to apply a recommendation and any parameters
          # to customize it.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     The resource name of the recommendation to apply.
          # @!attribute [rw] campaign_budget
          #   @return [Google::Ads::GoogleAds::V3::Services::ApplyRecommendationOperation::CampaignBudgetParameters]
          #     Optional parameters to use when applying a campaign budget
          #     recommendation.
          # @!attribute [rw] text_ad
          #   @return [Google::Ads::GoogleAds::V3::Services::ApplyRecommendationOperation::TextAdParameters]
          #     Optional parameters to use when applying a text ad recommendation.
          # @!attribute [rw] keyword
          #   @return [Google::Ads::GoogleAds::V3::Services::ApplyRecommendationOperation::KeywordParameters]
          #     Optional parameters to use when applying keyword recommendation.
          # @!attribute [rw] target_cpa_opt_in
          #   @return [Google::Ads::GoogleAds::V3::Services::ApplyRecommendationOperation::TargetCpaOptInParameters]
          #     Optional parameters to use when applying target CPA opt-in
          #     recommendation.
          # @!attribute [rw] callout_extension
          #   @return [Google::Ads::GoogleAds::V3::Services::ApplyRecommendationOperation::CalloutExtensionParameters]
          #     Parameters to use when applying callout extension recommendation.
          # @!attribute [rw] call_extension
          #   @return [Google::Ads::GoogleAds::V3::Services::ApplyRecommendationOperation::CallExtensionParameters]
          #     Parameters to use when applying call extension recommendation.
          # @!attribute [rw] sitelink_extension
          #   @return [Google::Ads::GoogleAds::V3::Services::ApplyRecommendationOperation::SitelinkExtensionParameters]
          #     Parameters to use when applying sitelink extension recommendation.
          # @!attribute [rw] move_unused_budget
          #   @return [Google::Ads::GoogleAds::V3::Services::ApplyRecommendationOperation::MoveUnusedBudgetParameters]
          #     Parameters to use when applying move unused budget recommendation.
          class ApplyRecommendationOperation
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Parameters to use when applying a campaign budget recommendation.
            # @!attribute [rw] new_budget_amount_micros
            #   @return [Google::Protobuf::Int64Value]
            #     New budget amount to set for target budget resource. This is a required
            #     field.
            class CampaignBudgetParameters
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end

            # Parameters to use when applying a text ad recommendation.
            # @!attribute [rw] ad
            #   @return [Google::Ads::GoogleAds::V3::Resources::Ad]
            #     New ad to add to recommended ad group. All necessary fields need to be
            #     set in this message. This is a required field.
            class TextAdParameters
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end

            # Parameters to use when applying keyword recommendation.
            # @!attribute [rw] ad_group
            #   @return [Google::Protobuf::StringValue]
            #     The ad group resource to add keyword to. This is a required field.
            # @!attribute [rw] match_type
            #   @return [Google::Ads::GoogleAds::V3::Enums::KeywordMatchTypeEnum::KeywordMatchType]
            #     The match type of the keyword. This is a required field.
            # @!attribute [rw] cpc_bid_micros
            #   @return [Google::Protobuf::Int64Value]
            #     Optional, CPC bid to set for the keyword. If not set, keyword will use
            #     bid based on bidding strategy used by target ad group.
            class KeywordParameters
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end

            # Parameters to use when applying Target CPA recommendation.
            # @!attribute [rw] target_cpa_micros
            #   @return [Google::Protobuf::Int64Value]
            #     Average CPA to use for Target CPA bidding strategy. This is a required
            #     field.
            # @!attribute [rw] new_campaign_budget_amount_micros
            #   @return [Google::Protobuf::Int64Value]
            #     Optional, budget amount to set for the campaign.
            class TargetCpaOptInParameters
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end

            # Parameters to use when applying callout extension recommendation.
            # @!attribute [rw] callout_extensions
            #   @return [Array<Google::Ads::GoogleAds::V3::Common::CalloutFeedItem>]
            #     Callout extensions to be added. This is a required field.
            class CalloutExtensionParameters
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end

            # Parameters to use when applying call extension recommendation.
            # @!attribute [rw] call_extensions
            #   @return [Array<Google::Ads::GoogleAds::V3::Common::CallFeedItem>]
            #     Call extensions to be added. This is a required field.
            class CallExtensionParameters
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end

            # Parameters to use when applying sitelink extension recommendation.
            # @!attribute [rw] sitelink_extensions
            #   @return [Array<Google::Ads::GoogleAds::V3::Common::SitelinkFeedItem>]
            #     Sitelink extensions to be added. This is a required field.
            class SitelinkExtensionParameters
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end

            # Parameters to use when applying move unused budget recommendation.
            # @!attribute [rw] budget_micros_to_move
            #   @return [Google::Protobuf::Int64Value]
            #     Budget amount to move from excess budget to constrained budget. This is
            #     a required field.
            class MoveUnusedBudgetParameters
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end
          end

          # Response message for [RecommendationService.ApplyRecommendation][google.ads.googleads.v3.services.RecommendationService.ApplyRecommendation].
          # @!attribute [rw] results
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::ApplyRecommendationResult>]
          #     Results of operations to apply recommendations.
          # @!attribute [rw] partial_failure_error
          #   @return [Google::Rpc::Status]
          #     Errors that pertain to operation failures in the partial failure mode.
          #     Returned only when partial_failure = true and all errors occur inside the
          #     operations. If any errors occur outside the operations (e.g. auth errors)
          #     we return the RPC level error.
          class ApplyRecommendationResponse
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # The result of applying a recommendation.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Returned for successful applies.
          class ApplyRecommendationResult
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # Request message for [RecommendationService.DismissRecommendation][google.ads.googleads.v3.services.RecommendationService.DismissRecommendation].
          # @!attribute [rw] customer_id
          #   @return [String]
          #     Required. The ID of the customer with the recommendation.
          # @!attribute [rw] operations
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::DismissRecommendationRequest::DismissRecommendationOperation>]
          #     Required. The list of operations to dismiss recommendations.
          #     If partial_failure=false all recommendations should be of the same type
          #     There is a limit of 100 operations per request.
          # @!attribute [rw] partial_failure
          #   @return [Boolean]
          #     If true, successful operations will be carried out and invalid
          #     operations will return errors. If false, operations will be carried in a
          #     single transaction if and only if they are all valid.
          #     Default is false.
          class DismissRecommendationRequest
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Operation to dismiss a single recommendation identified by resource_name.
            # @!attribute [rw] resource_name
            #   @return [String]
            #     The resource name of the recommendation to dismiss.
            class DismissRecommendationOperation
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end
          end

          # Response message for [RecommendationService.DismissRecommendation][google.ads.googleads.v3.services.RecommendationService.DismissRecommendation].
          # @!attribute [rw] results
          #   @return [Array<Google::Ads::GoogleAds::V3::Services::DismissRecommendationResponse::DismissRecommendationResult>]
          #     Results of operations to dismiss recommendations.
          # @!attribute [rw] partial_failure_error
          #   @return [Google::Rpc::Status]
          #     Errors that pertain to operation failures in the partial failure mode.
          #     Returned only when partial_failure = true and all errors occur inside the
          #     operations. If any errors occur outside the operations (e.g. auth errors)
          #     we return the RPC level error.
          class DismissRecommendationResponse
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # The result of dismissing a recommendation.
            # @!attribute [rw] resource_name
            #   @return [String]
            #     Returned for successful dismissals.
            class DismissRecommendationResult
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end
          end
        end
      end
    end
  end
end
