# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Enums
          # Container for enum describing possible types of a conversion action.
          class ConversionActionTypeEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Possible types of a conversion action.
            module ConversionActionType
              # Not specified.
              UNSPECIFIED = 0

              # Used for return value only. Represents value unknown in this version.
              UNKNOWN = 1

              # Conversions that occur when a user clicks on an ad's call extension.
              AD_CALL = 2

              # Conversions that occur when a user on a mobile device clicks a phone
              # number.
              CLICK_TO_CALL = 3

              # Conversions that occur when a user downloads a mobile app from the Google
              # Play Store.
              GOOGLE_PLAY_DOWNLOAD = 4

              # Conversions that occur when a user makes a purchase in an app through
              # Android billing.
              GOOGLE_PLAY_IN_APP_PURCHASE = 5

              # Call conversions that are tracked by the advertiser and uploaded.
              UPLOAD_CALLS = 6

              # Conversions that are tracked by the advertiser and uploaded with
              # attributed clicks.
              UPLOAD_CLICKS = 7

              # Conversions that occur on a webpage.
              WEBPAGE = 8

              # Conversions that occur when a user calls a dynamically-generated phone
              # number from an advertiser's website.
              WEBSITE_CALL = 9
            end
          end
        end
      end
    end
  end
end
