# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Enums
          # Container for enum describing possible data types for a feed attribute.
          class FeedAttributeTypeEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Possible data types for a feed attribute.
            module FeedAttributeType
              # Not specified.
              UNSPECIFIED = 0

              # Used for return value only. Represents value unknown in this version.
              UNKNOWN = 1

              # Int64.
              INT64 = 2

              # Double.
              DOUBLE = 3

              # String.
              STRING = 4

              # Boolean.
              BOOLEAN = 5

              # Url.
              URL = 6

              # Datetime.
              DATE_TIME = 7

              # Int64 list.
              INT64_LIST = 8

              # Double (8 bytes) list.
              DOUBLE_LIST = 9

              # String list.
              STRING_LIST = 10

              # Boolean list.
              BOOLEAN_LIST = 11

              # Url list.
              URL_LIST = 12

              # Datetime list.
              DATE_TIME_LIST = 13

              # Price.
              PRICE = 14
            end
          end
        end
      end
    end
  end
end
