# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Enums
          # Container for enumeration of keyword competition levels. The competition
          # level indicates how competitive ad placement is for a keyword and
          # is determined by the number of advertisers bidding on that keyword relative
          # to all keywords across Google. The competition level can depend on the
          # location and Search Network targeting options you've selected.
          class KeywordPlanCompetitionLevelEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Competition level of a keyword.
            module KeywordPlanCompetitionLevel
              # Not specified.
              UNSPECIFIED = 0

              # The value is unknown in this version.
              UNKNOWN = 1

              # Low competition.
              LOW = 2

              # Medium competition.
              MEDIUM = 3

              # High competition.
              HIGH = 4
            end
          end
        end
      end
    end
  end
end
