# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Enums
          # Container for enum describing plannable networks.
          class ReachPlanNetworkEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Possible plannable network values.
            module ReachPlanNetwork
              # Not specified.
              UNSPECIFIED = 0

              # Used as a return value only. Represents value unknown in this version.
              UNKNOWN = 1

              # YouTube network.
              YOUTUBE = 2

              # Google Video Partners (GVP) network.
              GOOGLE_VIDEO_PARTNERS = 3

              # A combination of the YouTube network and the Google Video Partners
              # network.
              YOUTUBE_AND_GOOGLE_VIDEO_PARTNERS = 4
            end
          end
        end
      end
    end
  end
end
