# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Enums
          # The user list types.
          class UserListTypeEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Enum containing possible user list types.
            module UserListType
              # Not specified.
              UNSPECIFIED = 0

              # Used for return value only. Represents value unknown in this version.
              UNKNOWN = 1

              # UserList represented as a collection of conversion types.
              REMARKETING = 2

              # UserList represented as a combination of other user lists/interests.
              LOGICAL = 3

              # UserList created in the Google Ad Manager platform.
              EXTERNAL_REMARKETING = 4

              # UserList associated with a rule.
              RULE_BASED = 5

              # UserList with users similar to users of another UserList.
              SIMILAR = 6

              # UserList of first-party CRM data provided by advertiser in the form of
              # emails or other formats.
              CRM_BASED = 7
            end
          end
        end
      end
    end
  end
end
