# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Enums
          # Supported rule operator for number type.
          class UserListNumberRuleItemOperatorEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Enum describing possible user list number rule item operators.
            module UserListNumberRuleItemOperator
              # Not specified.
              UNSPECIFIED = 0

              # Used for return value only. Represents value unknown in this version.
              UNKNOWN = 1

              # Greater than.
              GREATER_THAN = 2

              # Greater than or equal.
              GREATER_THAN_OR_EQUAL = 3

              # Equals.
              EQUALS = 4

              # Not equals.
              NOT_EQUALS = 5

              # Less than.
              LESS_THAN = 6

              # Less than or equal.
              LESS_THAN_OR_EQUAL = 7
            end
          end
        end
      end
    end
  end
end
