# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Resources
          # A Keyword Plan campaign.
          # Max number of keyword plan campaigns per plan allowed: 1.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Immutable. The resource name of the Keyword Plan campaign.
          #     KeywordPlanCampaign resource names have the form:
          #
          #     `customers/{customer_id}/keywordPlanCampaigns/{kp_campaign_id}`
          # @!attribute [rw] keyword_plan
          #   @return [Google::Protobuf::StringValue]
          #     The keyword plan this campaign belongs to.
          # @!attribute [r] id
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. The ID of the Keyword Plan campaign.
          # @!attribute [rw] name
          #   @return [Google::Protobuf::StringValue]
          #     The name of the Keyword Plan campaign.
          #
          #     This field is required and should not be empty when creating Keyword Plan
          #     campaigns.
          # @!attribute [rw] language_constants
          #   @return [Array<Google::Protobuf::StringValue>]
          #     The languages targeted for the Keyword Plan campaign.
          #     Max allowed: 1.
          # @!attribute [rw] keyword_plan_network
          #   @return [Google::Ads::GoogleAds::V3::Enums::KeywordPlanNetworkEnum::KeywordPlanNetwork]
          #     Targeting network.
          #
          #     This field is required and should not be empty when creating Keyword Plan
          #     campaigns.
          # @!attribute [rw] cpc_bid_micros
          #   @return [Google::Protobuf::Int64Value]
          #     A default max cpc bid in micros, and in the account currency, for all ad
          #     groups under the campaign.
          #
          #     This field is required and should not be empty when creating Keyword Plan
          #     campaigns.
          # @!attribute [rw] geo_targets
          #   @return [Array<Google::Ads::GoogleAds::V3::Resources::KeywordPlanGeoTarget>]
          #     The geo targets.
          #     Max number allowed: 20.
          class KeywordPlanCampaign
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end

          # A geo target.
          # Next ID: 3
          # @!attribute [rw] geo_target_constant
          #   @return [Google::Protobuf::StringValue]
          #     Required. The resource name of the geo target.
          class KeywordPlanGeoTarget
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
