# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Resources
          # A list of mutates being processed asynchronously. The mutates are uploaded
          # by the user. The mutates themselves aren't readable and the results of the
          # job can only be read using MutateJobService.ListMutateJobResults.
          # @!attribute [rw] resource_name
          #   @return [String]
          #     Immutable. The resource name of the mutate job.
          #     Mutate job resource names have the form:
          #
          #     `customers/{customer_id}/mutateJobs/{mutate_job_id}`
          # @!attribute [r] id
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. ID of this mutate job.
          # @!attribute [r] next_add_sequence_token
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The next sequence token to use when adding operations. Only set when the
          #     mutate job status is PENDING.
          # @!attribute [r] metadata
          #   @return [Google::Ads::GoogleAds::V3::Resources::MutateJob::MutateJobMetadata]
          #     Output only. Contains additional information about this mutate job.
          # @!attribute [r] status
          #   @return [Google::Ads::GoogleAds::V3::Enums::MutateJobStatusEnum::MutateJobStatus]
          #     Output only. Status of this mutate job.
          # @!attribute [r] long_running_operation
          #   @return [Google::Protobuf::StringValue]
          #     Output only. The resource name of the long-running operation that can be used to poll
          #     for completion. Only set when the mutate job status is RUNNING or DONE.
          class MutateJob
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Additional information about the mutate job. This message is also used as
            # metadata returned in mutate job Long Running Operations.
            # @!attribute [r] creation_date_time
            #   @return [Google::Protobuf::StringValue]
            #     Output only. The time when this mutate job was created.
            #     Formatted as yyyy-mm-dd hh:mm:ss. Example: "2018-03-05 09:15:00"
            # @!attribute [r] completion_date_time
            #   @return [Google::Protobuf::StringValue]
            #     Output only. The time when this mutate job was completed.
            #     Formatted as yyyy-MM-dd HH:mm:ss. Example: "2018-03-05 09:16:00"
            # @!attribute [r] estimated_completion_ratio
            #   @return [Google::Protobuf::DoubleValue]
            #     Output only. The fraction (between 0.0 and 1.0) of mutates that have been processed.
            #     This is empty if the job hasn't started running yet.
            # @!attribute [r] operation_count
            #   @return [Google::Protobuf::Int64Value]
            #     Output only. The number of mutate operations in the mutate job.
            # @!attribute [r] executed_operation_count
            #   @return [Google::Protobuf::Int64Value]
            #     Output only. The number of mutate operations executed by the mutate job.
            #     Present only if the job has started running.
            class MutateJobMetadata
              include Google::Protobuf::MessageExts
              extend Google::Protobuf::MessageExts::ClassMethods
            end
          end
        end
      end
    end
  end
end
