# frozen_string_literal: true

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Resources
          # A mobile operating system version or a range of versions, depending on
          # `operator_type`. List of available mobile platforms at
          # https://developers.google.com/adwords/api/docs/appendix/codes-formats#mobile-platforms
          # @!attribute [r] resource_name
          #   @return [String]
          #     Output only. The resource name of the operating system version constant.
          #     Operating system version constant resource names have the form:
          #
          #     `operatingSystemVersionConstants/{criterion_id}`
          # @!attribute [r] id
          #   @return [Google::Protobuf::Int64Value]
          #     Output only. The ID of the operating system version.
          # @!attribute [r] name
          #   @return [Google::Protobuf::StringValue]
          #     Output only. Name of the operating system.
          # @!attribute [r] os_major_version
          #   @return [Google::Protobuf::Int32Value]
          #     Output only. The OS Major Version number.
          # @!attribute [r] os_minor_version
          #   @return [Google::Protobuf::Int32Value]
          #     Output only. The OS Minor Version number.
          # @!attribute [r] operator_type
          #   @return [Google::Ads::GoogleAds::V3::Enums::OperatingSystemVersionOperatorTypeEnum::OperatingSystemVersionOperatorType]
          #     Output only. Determines whether this constant represents a single version or a range of
          #     versions.
          class OperatingSystemVersionConstant
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
