# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Errors
          # Container for enum describing possible account budget proposal errors.
          class AccountBudgetProposalErrorEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Enum describing possible account budget proposal errors.
            module AccountBudgetProposalError
              # Enum unspecified.
              UNSPECIFIED = 0

              # The received error code is not known in this version.
              UNKNOWN = 1

              # The field mask must be empty for create/end/remove proposals.
              FIELD_MASK_NOT_ALLOWED = 2

              # The field cannot be set because of the proposal type.
              IMMUTABLE_FIELD = 3

              # The field is required because of the proposal type.
              REQUIRED_FIELD_MISSING = 4

              # Proposals that have been approved cannot be cancelled.
              CANNOT_CANCEL_APPROVED_PROPOSAL = 5

              # Budgets that haven't been approved cannot be removed.
              CANNOT_REMOVE_UNAPPROVED_BUDGET = 6

              # Budgets that are currently running cannot be removed.
              CANNOT_REMOVE_RUNNING_BUDGET = 7

              # Budgets that haven't been approved cannot be truncated.
              CANNOT_END_UNAPPROVED_BUDGET = 8

              # Only budgets that are currently running can be truncated.
              CANNOT_END_INACTIVE_BUDGET = 9

              # All budgets must have names.
              BUDGET_NAME_REQUIRED = 10

              # Expired budgets cannot be edited after a sufficient amount of time has
              # passed.
              CANNOT_UPDATE_OLD_BUDGET = 11

              # It is not permissible a propose a new budget that ends in the past.
              CANNOT_END_IN_PAST = 12

              # An expired budget cannot be extended to overlap with the running budget.
              CANNOT_EXTEND_END_TIME = 13

              # A purchase order number is required.
              PURCHASE_ORDER_NUMBER_REQUIRED = 14

              # Budgets that have a pending update cannot be updated.
              PENDING_UPDATE_PROPOSAL_EXISTS = 15

              # Cannot propose more than one budget when the corresponding billing setup
              # hasn't been approved.
              MULTIPLE_BUDGETS_NOT_ALLOWED_FOR_UNAPPROVED_BILLING_SETUP = 16

              # Cannot update the start time of a budget that has already started.
              CANNOT_UPDATE_START_TIME_FOR_STARTED_BUDGET = 17

              # Cannot update the spending limit of a budget with an amount lower than
              # what has already been spent.
              SPENDING_LIMIT_LOWER_THAN_ACCRUED_COST_NOT_ALLOWED = 18

              # Cannot propose a budget update without actually changing any fields.
              UPDATE_IS_NO_OP = 19

              # The end time must come after the start time.
              END_TIME_MUST_FOLLOW_START_TIME = 20

              # The budget's date range must fall within the date range of its billing
              # setup.
              BUDGET_DATE_RANGE_INCOMPATIBLE_WITH_BILLING_SETUP = 21

              # The user is not authorized to mutate budgets for the given billing setup.
              NOT_AUTHORIZED = 22

              # Mutates are not allowed for the given billing setup.
              INVALID_BILLING_SETUP = 23
            end
          end
        end
      end
    end
  end
end
