# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Errors
          # Container for enum describing possible ad group errors.
          class AdGroupErrorEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Enum describing possible ad group errors.
            module AdGroupError
              # Enum unspecified.
              UNSPECIFIED = 0

              # The received error code is not known in this version.
              UNKNOWN = 1

              # AdGroup with the same name already exists for the campaign.
              DUPLICATE_ADGROUP_NAME = 2

              # AdGroup name is not valid.
              INVALID_ADGROUP_NAME = 3

              # Advertiser is not allowed to target sites or set site bids that are not
              # on the Google Search Network.
              ADVERTISER_NOT_ON_CONTENT_NETWORK = 5

              # Bid amount is too big.
              BID_TOO_BIG = 6

              # AdGroup bid does not match the campaign's bidding strategy.
              BID_TYPE_AND_BIDDING_STRATEGY_MISMATCH = 7

              # AdGroup name is required for Add.
              MISSING_ADGROUP_NAME = 8

              # No link found between the ad group and the label.
              ADGROUP_LABEL_DOES_NOT_EXIST = 9

              # The label has already been attached to the ad group.
              ADGROUP_LABEL_ALREADY_EXISTS = 10

              # The CriterionTypeGroup is not supported for the content bid dimension.
              INVALID_CONTENT_BID_CRITERION_TYPE_GROUP = 11

              # The ad group type is not compatible with the campaign channel type.
              AD_GROUP_TYPE_NOT_VALID_FOR_ADVERTISING_CHANNEL_TYPE = 12

              # The ad group type is not supported in the country of sale of the
              # campaign.
              ADGROUP_TYPE_NOT_SUPPORTED_FOR_CAMPAIGN_SALES_COUNTRY = 13

              # Ad groups of AdGroupType.SEARCH_DYNAMIC_ADS can only be added to
              # campaigns that have DynamicSearchAdsSetting attached.
              CANNOT_ADD_ADGROUP_OF_TYPE_DSA_TO_CAMPAIGN_WITHOUT_DSA_SETTING = 14
            end
          end
        end
      end
    end
  end
end
