# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Errors
          # Container for enum describing possible conversion action errors.
          class ConversionActionErrorEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Enum describing possible conversion action errors.
            module ConversionActionError
              # Enum unspecified.
              UNSPECIFIED = 0

              # The received error code is not known in this version.
              UNKNOWN = 1

              # The specified conversion action name already exists.
              DUPLICATE_NAME = 2

              # Another conversion action with the specified app id already exists.
              DUPLICATE_APP_ID = 3

              # Android first open action conflicts with Google play codeless download
              # action tracking the same app.
              TWO_CONVERSION_ACTIONS_BIDDING_ON_SAME_APP_DOWNLOAD = 4

              # Android first open action conflicts with Google play codeless download
              # action tracking the same app.
              BIDDING_ON_SAME_APP_DOWNLOAD_AS_GLOBAL_ACTION = 5

              # The attribution model cannot be set to DATA_DRIVEN because a data-driven
              # model has never been generated.
              DATA_DRIVEN_MODEL_WAS_NEVER_GENERATED = 6

              # The attribution model cannot be set to DATA_DRIVEN because the
              # data-driven model is expired.
              DATA_DRIVEN_MODEL_EXPIRED = 7

              # The attribution model cannot be set to DATA_DRIVEN because the
              # data-driven model is stale.
              DATA_DRIVEN_MODEL_STALE = 8

              # The attribution model cannot be set to DATA_DRIVEN because the
              # data-driven model is unavailable or the conversion action was newly
              # added.
              DATA_DRIVEN_MODEL_UNKNOWN = 9
            end
          end
        end
      end
    end
  end
end
