# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Errors
          # Container for enum describing possible custom interest errors.
          class CustomInterestErrorEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Enum describing possible custom interest errors.
            module CustomInterestError
              # Enum unspecified.
              UNSPECIFIED = 0

              # The received error code is not known in this version.
              UNKNOWN = 1

              # Duplicate custom interest name ignoring case.
              NAME_ALREADY_USED = 2

              # In the remove custom interest member operation, both member ID and
              # pair [type, parameter] are not present.
              CUSTOM_INTEREST_MEMBER_ID_AND_TYPE_PARAMETER_NOT_PRESENT_IN_REMOVE = 3

              # The pair of [type, parameter] does not exist.
              TYPE_AND_PARAMETER_NOT_FOUND = 4

              # The pair of [type, parameter] already exists.
              TYPE_AND_PARAMETER_ALREADY_EXISTED = 5

              # Unsupported custom interest member type.
              INVALID_CUSTOM_INTEREST_MEMBER_TYPE = 6

              # Cannot remove a custom interest while it's still being targeted.
              CANNOT_REMOVE_WHILE_IN_USE = 7

              # Cannot mutate custom interest type.
              CANNOT_CHANGE_TYPE = 8
            end
          end
        end
      end
    end
  end
end
