# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Errors
          # Container for enum describing possible feed item target errors.
          class FeedItemTargetErrorEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Enum describing possible feed item target errors.
            module FeedItemTargetError
              # Enum unspecified.
              UNSPECIFIED = 0

              # The received error code is not known in this version.
              UNKNOWN = 1

              # On CREATE, the FeedItemTarget must have a populated field in the oneof
              # target.
              MUST_SET_TARGET_ONEOF_ON_CREATE = 2

              # The specified feed item target already exists, so it cannot be added.
              FEED_ITEM_TARGET_ALREADY_EXISTS = 3

              # The schedules for a given feed item cannot overlap.
              FEED_ITEM_SCHEDULES_CANNOT_OVERLAP = 4

              # Too many targets of a given type were added for a single feed item.
              TARGET_LIMIT_EXCEEDED_FOR_GIVEN_TYPE = 5

              # Too many AdSchedules are enabled for the feed item for the given day.
              TOO_MANY_SCHEDULES_PER_DAY = 6

              # A feed item may either have an enabled campaign target or an enabled ad
              # group target.
              CANNOT_HAVE_ENABLED_CAMPAIGN_AND_ENABLED_AD_GROUP_TARGETS = 7

              # Duplicate ad schedules aren't allowed.
              DUPLICATE_AD_SCHEDULE = 8

              # Duplicate keywords aren't allowed.
              DUPLICATE_KEYWORD = 9
            end
          end
        end
      end
    end
  end
end
