# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Errors
          # Container for enum describing possible errors from applying a keyword plan
          # campaign.
          class KeywordPlanCampaignErrorEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Enum describing possible errors from applying a keyword plan campaign.
            module KeywordPlanCampaignError
              # Enum unspecified.
              UNSPECIFIED = 0

              # The received error code is not known in this version.
              UNKNOWN = 1

              # A keyword plan campaign name is missing, empty, longer than allowed limit
              # or contains invalid chars.
              INVALID_NAME = 2

              # A keyword plan campaign contains one or more untargetable languages.
              INVALID_LANGUAGES = 3

              # A keyword plan campaign contains one or more invalid geo targets.
              INVALID_GEOS = 4

              # The keyword plan campaign name is duplicate to an existing keyword plan
              # campaign name or other keyword plan campaign name in the request.
              DUPLICATE_NAME = 5

              # The number of geo targets in the keyword plan campaign exceeds limits.
              MAX_GEOS_EXCEEDED = 6
            end
          end
        end
      end
    end
  end
end
