# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V3
        module Errors
          # Container for enum describing possible media uploading errors.
          class MediaUploadErrorEnum
            include Google::Protobuf::MessageExts
            extend Google::Protobuf::MessageExts::ClassMethods

            # Enum describing possible media uploading errors.
            module MediaUploadError
              # Enum unspecified.
              UNSPECIFIED = 0

              # The received error code is not known in this version.
              UNKNOWN = 1

              # The uploaded file is too big.
              FILE_TOO_BIG = 2

              # Image data is unparseable.
              UNPARSEABLE_IMAGE = 3

              # Animated images are not allowed.
              ANIMATED_IMAGE_NOT_ALLOWED = 4

              # The image or media bundle format is not allowed.
              FORMAT_NOT_ALLOWED = 5

              # Cannot reference URL external to the media bundle.
              EXTERNAL_URL_NOT_ALLOWED = 6

              # HTML5 ad is trying to reference an asset not in .ZIP file.
              INVALID_URL_REFERENCE = 7

              # The media bundle contains no primary entry.
              MISSING_PRIMARY_MEDIA_BUNDLE_ENTRY = 8
            end
          end
        end
      end
    end
  end
end
